### ISSUE TITLE
Type as URI

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#104]
On https://github.com/w3ctag/spec-reviews/issues/37 @domenic said:

I think the core of my issue is envisioning someone designing a HTTP API, perhaps someone who hasn't bought into REST all that much. They might naively expect something like { "type": "not_enough_money" }. Being told that they have to convert this to { "type": "https://api.example.com/error-types/not_enough_money" } could cause them to abandon this spec on first read-through as not suited for their server. If they could simply do { "type": "not_enough_money" }, that would be great. If they instead had to do { "type": "about:not_enough_money" } or something, that might also be OK. Remember that we don't need to be globally unique here---we just need to be unique per-API.

What are your thoughts on this perspective? When you talk about possibly-relative URLs, do you mean that { "type": "not_enough_money" } is fine, since technically it fits the grammar of a relative URL?

**Comment by akuckartz** [comment]
The alternative
> { "type": "https://api.example.com/error-types/not_enough_money" } 
might be an option if the URL is not required to be dereferencable.
