### ISSUE TITLE
Extension namespacing

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#107]
Brought up by @domenic in https://github.com/w3ctag/spec-reviews/issues/37 .

Suggestion is either to reserve syntax (e.g., "-" in keys), or have an explicit extension object.

**Comment by dret** [comment]
Since we also define an alternative XML serialization, it would be good to make sure that whatever the extension convention is, it maps reasonably into XML. Using XML namespaces probably would not be a good way to go, so the XML would simply reflect the JSON convention.

**Comment by mnot** [comment]
I'm a *little* bit sensitive to people who are already using the format; don't want to break them unnecessarily. 

How about defining a container for extensions to go into, and then saying that other unrecognised root members need to be ignored? That would allow future standard extension as well as existing ad hoc uses.

Question is, what to call it? "payload"? "ext"? "extra"?

**Comment by dret** [comment]
could you please give a short JSON example of what you're thinking of? that would help, and then i can also see how (well) this would map for the XML representation. if there's such a mechanism, there should be examples of it in the spec anyway, right?

**Comment by mnot** [comment]
The existing example in the spec is:

```json
{
 "type": "https://example.com/probs/out-of-credit",
 "title": "You do not have enough credit.",
 "detail": "Your current balance is 30, but that costs 50.",
 "instance": "/account/12345/msgs/abc",
 "balance": 30,
 "accounts": ["/account/12345",
              "/account/67890"]
}
```

... which I'm saying should become something like:

```json
{
 "type": "https://example.com/probs/out-of-credit",
 "title": "You do not have enough credit.",
 "detail": "Your current balance is 30, but that costs 50.",
 "instance": "/account/12345/msgs/abc",
 "vars": {
   "balance": 30,
   "accounts": ["/account/12345",
                "/account/67890"]
  }
}
```

(delta the name of the thing)

**Comment by dret** [comment]
not sure that this was part of the suggestion, but if there are "extension objects", another possibility would be to have an array of them and have identifiers (most likely URIs) for them, so that extensions would be packaged and labeled. maybe that's overkill, but if we're trying to separate "well-known" and "extension" properties, we might as well structure the extensions. the downside is that the simple example now becomes even more complicated:
```javascript
{
  "type": "https://example.com/probs/out-of-credit",
  "title": "You do not have enough credit.",
  "detail": "Your current balance is 30, but that costs 50.",
  "instance": "/account/12345/msgs/abc",
  "ext": [
    { "http://example.com/extension42": {
        "balance": 30,
        "accounts": [ "/account/12345", "/account/67890" ] } }
  ]
}
```

**Comment by mnot** [comment]
That seems like a barrier to entry / use...

**Comment by dret** [comment]
so then the model is to have one unstructured bag of extension properties and they go all in there? then the wording about disallowing extensions on the outer level should be rather strong, i assume.

**Comment by darrelmiller** [comment]
I was just discussing the issue of extension properties with @mamund and some audience members after at talk at NDC Oslo where I was showing HTTP Problem.  I really like the fact that there is no structural difference between standard properties and extension properties.  It has the benefit that if some extension property becomes popular it could be adapted into the specification without impacting existing users.

If there is a naming conflict between some app-specific extension property and the standard properties then the app-specific properties could be embedded in their own namespacing object.

The only downside I can see is if http-problem is updated to include new properties then there may be conflicts with users who have created extension properties with the same name with different semantics.  This seems like the same problem we have with HTTP headers and if users are concerned  about this property then prefixing with a company specific prefix will likely solve that.

The "ext" object feels a whole lot like x- to me.  If you have multiple pieces of middleware that want to add error/tracing related details to a http-problem payload on the return path, the problem of namespacing returns but this time within the "ext" object.

**Comment by mamund** [comment]
In Cj, the decision was lean on MUST-IGNORE behavior and allow added properties and objects as long as there was a "registered extension" in the standards repo. This provides some barrier to entry and review that is helpful. but it still runs the risk of collisions.

In UBER the thinking is closer to @mnot's example here -- a named element of some type. in UBER we plan to use a common element for all extensions and, like @dret suggests,  a unique identifier for each of them (`{"extends: {"id":"...", ....}}`). That ID _might_ be a URI, simple name, etc. -- no decision yet. The ID will be the point of MUST-IGNORE.

The Cj pattern offers very easy extension w/o much ceremony even at runtime but we often see pll extending Cj w/o registering and that has the _potential_ of incompatibility (we haven't seen any real pain from this tho). The UBER pattern offers more isolation, but added structure as a downside.

**Comment by mnot** [comment]
@darrelmiller - The problem is that it'll be a huge judgement call as to whether to prefix your extension based upon whether you think it might eventually gets into the "standard" space or not. 

History shows us that people have a really hard time making that determination well; lots of things that are app-specific get into the "standard" space (because people don't care or don't have time to read the docs), and lots of things that *could* be standard get prefixed (because careful people who read the docs get conservative).

**Comment by mnot** [comment]
Another option would be to not change anything, but require any future version of the spec to use a different media type.

**Comment by dret** [comment]
just as a data point: https://tools.ietf.org/html/rfc6648 (@mnot is co-author, so no surprises here).
