### ISSUE TITLE
HTTP problem spec is expired

### ISSUE THREAD

**Issue by kevinburkeshyp** [mnot/I-D#112]
The latest version of the HTTP problem spec (that I can find, anyway) indicates March 23, 2015 as the expiration date: https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00

Is there a new draft?

**Comment by mnot** [comment]
Not yet; we have some issues to work through.

BTW, it's better to ask on the mailing list (apps-discuss@ietf.org, as mentioned in the draft) than create an issue for this sort of thing.
