### ISSUE TITLE
Question: Status of json-home?

### ISSUE THREAD

**Issue by jrnail23** [mnot/I-D#114]
Just wanted to ask about the current status of the json-home draft... I noticed that v3 expired quite a while back.  Will it be updated anytime soon, has it been abandoned, or is it considered complete?
Also, as of v3, representation hints were listed as "TBD" -- has any progress been made on that, or should they simply be ignored when implementing json-home?

Thanks in advance!

**Comment by mnot** [comment]
Just on the back burner; will dust it off soon. Not sure about hints yet.

**Comment by jrnail23** [comment]
Thanks for the update, @mnot.
