### ISSUE TITLE
value neutrality

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#121]
Harald points out that the IETF is *not* neutral -- we have values. If we don't, we're merely a meeting place.

This has most implication upon the introduction.

**Comment by mnot** [comment]
Because our decisions have ethical implications, we must consider them, and determine whether they're within our core values. We do so in a well-defined open fashion.

**Comment by mnot** [comment]
If something reduces openness, we're against it.

**Comment by akuckartz** [comment]
:+1:
