### ISSUE TITLE
Whitespace requirement might be too harsh

### ISSUE THREAD

**Issue by yoavweiss** [mnot/I-D#131]
`Whitespace is not allowed in the field-value between each field-name and its parameter set.`

As a potential implementor it makes the parsing algorithm simpler, but I'm also afraid it'd create a subtle way in which people would fail to deploy this syntax in real life.

Since supporting whitespace won't add significant complexity to the parsing algorithm, can we allow it?

**Comment by mnot** [comment]
Moving to http-extensions repo.
