### ISSUE TITLE
Flag value

### ISSUE THREAD

**Issue by alagoutte** [mnot/I-D#134]
On H2, other frame type (DATA, HEADERS, PUSH_PROMISE) use always 0x08 to say, there is pad stuff

May be also use bit6 for IPv6 flag on IP / HTTP2 frame type ?

**Comment by mnot** [comment]
Sounds reasonable. I'm not spending much time on this spec right now, as it's not clear to me that it's the right way forward, and also I need some implementer interest :)

**Comment by mnot** [comment]
QUIC is probably better for VPNs at this point, and AIUI some people are looking at this. Closing.
