### ISSUE TITLE
First strategy for generating secondary keys infers request doesn't need to be stored

### ISSUE THREAD

**Issue by darrelmiller** [mnot/I-D#136]
In section 2.2. the first strategy says..
> Generating a new secondary cache key for every stored response associated with the resource upon each request.

In order to achieve this, wouldn't the request headers for each stored response need to be cached also?  The next strategy explicitly calls out this requirement,
> with the stored request/response pair 

I must admit, I'm a bit leery about the idea of caches choosing to store authorization headers just in case one day a future key header decides to include it.  I think I would prefer the invalidate all variants if the key changes approach.

**Comment by mnot** [comment]
Authorization headers always imply a private response, see http://httpwg.github.io/specs/rfc7234.html#response.cacheability

Regardless, there are a number of ways to do this, and not all require storing requests; re-read the text around the second quote above. :)

**Comment by darrelmiller** [comment]
Just because the request headers are only cached privately does mean there is not a risk associated to it... http://blog.parse.com/learn/engineering/discovering-a-major-security-hole-in-facebooks-android-sdk/
And if someone happens to use a must-revalidate header, the authenticated response can be cached. I've never really understood that relation.

I still don't see how storing all the request headers can be avoided unless you take the third strategy but maybe it will get clearer to me when I actually try implementing it.

**Comment by mnot** [comment]
Keep in mind that Vary also requires storing the relevant request headers.

**Comment by darrelmiller** [comment]
Exactly.  But you only need to store the request headers mentioned in the vary header at the time of the request.  If the vary header adds a new field name at a later date, you do not need to know what that request header value was for the stored responses for that new vary header field.  Previously stored responses are only evaluated based on what the vary header was at the time it was stored.

The only way you can keep a stored response around when a key header adds a new field name is if you have the request header already stored.  But how do we predict what fields might be added to a key header might be added in the future?
