### ISSUE TITLE
"semantically equivalent"

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#141]
> [the link header field] is semantically equivalent to the &lt;LINK&gt; element in HTML, as well as the atom:link feed-level element in Atom.

No, it's not; an application has to opt into using the link header field.

**Comment by asbjornu** [comment]
@mnot Even though it is not semantically equivalent, don't you think it's good to at least reference the `<link>` and `atom:link` elements to provide some context? Once the `Link` header is present, it provides very similar semantics to the two `link` elements. How about:

> The Link entity-header field provides a means for serialising one or more links in HTTP headers. When present, it is semantically equivalent to the `<LINK>` element in HTML, as well as the `atom:link` feed-level element in Atom {{RFC4287}}.

**Comment by mnot** [comment]
That's just as confusing. The point is that an application (e.g., web browsing with HTML) has to opt into using the Link header; e.g., rel=stylesheet isn't defined for that, so it doesn't work.

**Comment by asbjornu** [comment]
Good point! I thought "an application has to opt into using the link header field" was the only reason the semantics were different, but `rel="stylesheet"` indeed shows that there's more separating them. Perhaps something should be said to that effect, then? I.e. that while the `Link` header looks similar to `<link>` and `atom:link` and even share quite a few `rel` values, they are in fact different?
