### ISSUE TITLE
Error handling on Link headers

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#143]
- syntax recovery
- multiple instances of [rel, target attributes]

**Comment by mnot** [comment]
@reschke - IIRC you have some tests for Link; where are they?

@annevk, any useful references / thoughts?

**Comment by reschke** [comment]
I have a few tests here: http://greenbytes.de/tech/tc/httplink/, but they do not cover error handling.

**Comment by annevk** [comment]
No, sorry. Just that it would be good to have this defined.

**Comment by jasnell** [comment]
Definitely would be great to have the multiple instances of [rel, target attributes] dealt with. For [LINK/UNLINK](https://tools.ietf.org/html/draft-snell-link-method-12) these would be handled as entirely separate, independent Links so it would be good to have this clearly defined.

**Comment by asbjornu** [comment]
As I mention in #170, some guidance on this in the RFC would be excellent. Also, a full test suite (referenced from the RFC) would be **awesome**.

**Comment by mnot** [comment]
OK, I've started a parsing appendix. I think the multiple reps (etc.) issue is already clear in the text now (thanks @asbjornu).

@annevk et al would you please do a quick sanity check on the commit above?

Also at:
  http://mnot.github.io/I-D/rfc5988bis/?#parse

**Comment by annevk** [comment]
Looks reasonable, though I suspect in practice browsers probably assume UTF-8 as encoding, or maybe multiple encodings if parsing headers mostly goes in terms of bytes (initially).

You'll need to define "whitespace". Also URLs...

**Comment by mnot** [comment]
@annevk - thanks, have defined whitespace, will punt on URL for now :)

WRT encoding - firefox appears to assume ISO-8859-1 encoding (at least for title on rel=stylesheet); see:
http://test.mnot.net/foo/

That's actually based upon the original definition of the title attribute of Link, which used the `quoted-pair` ABNF from 2616 (and predecessors), which referred to the `TEXT` ABNF, which was explicitly 8859-1.

That kind of sucks; see #180. Closing this (it's been sketched in and we can always open new issues), and moving discussion of encoding over there.

**Comment by annevk** [comment]
I mainly suspect the URL to be UTF-8.

**Comment by mnot** [comment]
Nope; it appears to assume 8859-1 in the URL too.

**Comment by mnot** [comment]
Testing a bit more with Location (since only FF honours Link rel=stylesheet), it appears that when non-ascii characters appear in the URL, the bytes are just percent-encoded as is.

E.g., if I send UTF-8 `ü` on the wire in Location, the resulting URL will have `%C3%BC`. If I send ISO-8859-1, it'll be `%FC`. 

Tested with FF and Chrome.

**Comment by annevk** [comment]
That makes sense.
