### ISSUE TITLE
Avoid clashing of URI relation types, and the "pseudo URIs" for registered types

### ISSUE THREAD

**Issue by dret** [mnot/I-D#145]
depending on what #140 proposes as the prefix to "URIfy" registered strings, maybe the section on URIs as "non-registered relation types" should mention that prefix explicitly and state than extension types MUST NOT use that prefix? if that sounds reasonable, i could add something to that effect.

**Comment by elf-pavlik** [comment]
:+1:
It could also recommend to either reuse exiting URIs, which one can find in aggregation services like http://lov.okfn.org/dataset/lov/ or offer guidance on how to choose appropriate namespace for defining a new URI e.g. for HTTP URIs a domain name under one's own control.

**Comment by dschulten** [comment]
+1

**Comment by asbjornu** [comment]
Yes. Something like this:

1. Registered strings **must not** be prefixed in environments where they are recognized (such as `text/html`, `Link` headers and `application/atom+xml`)
2. Registered strings **should** be prefixed in environments where they are not recognized (such as RDFa, JSON-LD, etc.)

The list should probably be longer, but it's a start.

**Comment by mnot** [comment]
Closing, based upon the changes above.

**Comment by dret** [comment]
i commented on the commit, it seems to be at odds with the current state of #140.

**Comment by mnot** [comment]
Would removing the "These URIs also..." sentence work for everyone?

**Comment by dret** [comment]
works for me. since i opened this issue: this was meant as a clean-up item in case there was a change to the spec turning registered strings into URIs, or allowed URIs as aliases. afaict, that's currently not the case, and thus this issue does not apply (yet).

**Comment by asbjornu** [comment]
@mnot Works for me. :+1:
