### ISSUE TITLE
More repositories, please

### ISSUE THREAD

**Issue by asbjornu** [mnot/I-D#150]
Sorry about this, but I just want to raise this to make it a bit easier to collaborate on the pretty large amounts of RFC's you've contributed to, @mnot. Since there are a lot of RFC's and increasing interest in them, there's now quite a bit of activity in issues, discussions and pull requests that are mostly completely unrelated.

Even though it involves a bit of work, I think it would be wise to separate each RFC into its own repository, so they get their own revision history, their own related issues, pull requests, etc. Although that means each repository becomes very small, it will make everything a bit more organized and easier to follow. Perhaps not so much for you, but at least for everyone else who might not be interested in all of the ongoing I-D work, but just in that of a few specific RFC's.

In order to separate the repositories, you can quite easily [move a subdirectory of your current repository into a new repository](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/) and then [move all related issues to the new repository](https://github.com/google/github-issue-mover). I'd love to help you out, so please let me know if you think this is a good idea or not and whether you'd like help doing it.

**Comment by dret** [comment]
i am interested to see what @mnot thinks about this...

**Comment by mnot** [comment]
I think that I'm not a standards body, and people shouldn't give too much weight to what I do here; these are all proto-specs. Administratively, it's MUCH easier for me to have these all in one repo.

That said, if 5988bis (or any other spec) is adopted somewhere, I'll be happy to split it off (assuming the work stays in my repo and doesn't move elsewhere anyway).

**Comment by asbjornu** [comment]
> I think that I'm not a standards body

You're too humble! ;-)

> and people shouldn't give too much weight to what I do here; these are all proto-specs. Administratively, it's MUCH easier for me to have these all in one repo.

I understand. Okay, then. Moving on. :-)
