### ISSUE TITLE
Remove/Deprecate "Link Relation Application Data Registry"

### ISSUE THREAD

**Issue by dret** [mnot/I-D#152]
http://tools.ietf.org/html/rfc5988#section-6.3 defines a "Link Relation Application Data Registry", which never caught on. http://www.iana.org/assignments/link-relations/link-relations.xhtml#link-relations-2 has zero entries, and a successor of RFC 5988 probably should take note and either get rid of the registry altogether (if that's even possible), or mention that this one never saw adoption (and maybe also suggest that new registrations shouldn't be made).

**Comment by mnot** [comment]
Dup of #37.

**Comment by dret** [comment]
searched the issues beforehand but did not find #37, and yes, this here is a duplicate.
