### ISSUE TITLE
Expert decisions

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#163]
Assuming that the experts remain, how they interact with IANA needs to be clarified to indicate whether there needs to be consensus among the experts, or whether first answer is sufficient.

**Comment by dret** [comment]
given the history of expert feedback, at least having some time-out might be advisable. it seemed often that the biggest bottleneck of the registration isn't the process itself, but the sometimes long delays to get through it.

**Comment by mnot** [comment]
Talking to Michelle C, this seems like something that the experts and ICANN can work out in the background, no need to specify it up-front.
