### ISSUE TITLE
Duplicate links

### ISSUE THREAD

**Issue by asbjornu** [mnot/I-D#170]
I can't find the word "duplicate" or any variation thereof in RFC 5899 explaining how to handle duplicate links and what should be considered duplicate links. If two links have the same `rel` value, but different target URIs, should both be considered "valid" and if so, how should a client find the correct one between the two?

If the two links have `type`, `title` or other parameters that distinguish them, then that helps, but since these parameters are optional, I'd appreciate some explanation on what to do when the links have duplicate `rel` values.

Seen from an implementation perspective, you'd be likely to choose a dictionary where the `rel` value in some form or another is used as a lookup key, returning one or more links with a matching `rel` parameter. Should the implementation of RFC 5899 not care about duplicates, leaving that problem up to the client application or user, or should duplicates be handled in some prescribed, algorithmic way?

**Comment by mnot** [comment]
In Section 3 of 5988:

> This specification does not place restrictions on the cardinality of links; there can be multiple links to and from a particular IRI, and multiple links of different types between two given IRIs.  Likewise, the relative ordering of links in any particular serialisation, or between serialisations (e.g., the Link header and in-content links) is not specified or significant in this specification; applications that wish to consider ordering significant can do so.

The current draft makes a slight change to this (relevant part **bolded**):

> This specification does not place restrictions on the cardinality of links; there can be multiple links to and from a particular target, and multiple links of **the same or** different types between a given context and target. Likewise, the relative ordering of links in any particular serialisation, or between serialisations (e.g., the Link header and in-content links) is not specified or significant in this specification; applications that wish to consider ordering significant can do so.

**Comment by asbjornu** [comment]
As an implementor, I'm still confused on how to treat duplicate links, parameters, etc. Is this specified in another RFC and if so, shouldn't RFC 5899 reference it? When parsing the following link, what should I do?

```
Link: </up-or-first>; rel="up"; rel="first"
```

What's the link relation here, `up` or `first`? And how about the following:

```
Link: </up>; rel="up", </up.html>; rel="up"
```

Which link should be considered to be authoritative for the "up" relation? Should the RFC say anything about this, or at least that a `type` parameter `SHOULD` be added given such duplication, to give the client a way of differentiating the two links from each other?

**Comment by asbjornu** [comment]
@mnot After reading the RFC a bit more closely, I've now found a few sections making it clearer what to do with duplicate parameters:

Section 5.3 states:
> The "rel" parameter MUST NOT appear more than once in a given link-value; occurrences after the first MUST be ignored by parsers.

Section 5.4 states:
> The "title" parameter MUST NOT appear more than once in a given link-value; occurrences after the first MUST be ignored by parsers.

Section 5.4 states:
> There MUST NOT be more than one type parameter in a link-value.

I think the last section here relating to `type` could be made clearer as the others on what to do. For consistency, I suggest that the section be changed to:

> The "type" parameter MUST NOT appear more than once in a given link-value; occurrences after the first MUST be ignored by parsers.

So now I'm only wondering about what to do about duplicate `link-value`s in the header. Although the specification states that it places no restriction on the cardinality of links, it's hard to know what to do when parsing a header and finding several that semantically are equal.

If a link is equal to another down to the octet, should it be added or ignored?

**Comment by asbjornu** [comment]
What should be done with parameters not defined in RFC 5899? Are they at all allowed and if they are, what should be done with duplicates?

**Comment by mnot** [comment]
> If a link is equal to another down to the octet, should it be added or ignored?

Do you mean a link that has the same target, context, relation type and attributes? 

I think it's *probably* safe to fold those into one, unless the application is something like "counting links" -- after all, an HTML page can (and often does) have duplicate links.

From an abstract library standpoint, it's probably safer to leave them separate.

WRT parameters -- assuming you're talking about target attributes more generally, they are allowed, and duplicates can occur. Unless the defining party (typically either the rel type or the application) says they can't.

**Comment by asbjornu** [comment]
> Do you mean a link that has the same target, context, relation type and attributes?

Yep.

> I think it's probably safe to fold those into one, unless the application is something like "counting links" -- after all, an HTML page can (and often does) have duplicate links.

True, but an HTML page also has a lot of more context than an HTTP `Link` header, especially if you're talking about the `a` element.

> From an abstract library standpoint, it's probably safer to leave them separate.

Should the RFC state anything in this regard, so libraries have the same behavior? Personally, I find it a bit silly to keep all of the following links separate:

```http
Link: </alternate>; rel="alternate",
      </alternate>; rel="AlterNate",
      </alternate>; rel="ALTERNATE",
      </alternate>; rel="alternate",
      </alternate>; rel="http://www.iana.org/assignments/relation/alternate"
```

Semantically, they're all **exactly** the same, according to the RFC, unless I've misunderstood something. Seeing how `rel` is a natural key on which to look up links, it makes the example above difficult to handle if the links are to be kept separate.

> WRT parameters -- assuming you're talking about target attributes more generally, they are allowed, and duplicates can occur. Unless the defining party (typically either the rel type or the application) says they can't.

Right. Does the RFC say anything about this already? Since the RFC is explicit about `type`, `rel`, etc. not being duplicate, it's natural (to me, anyways) to treat all parameters the same and add them as non-duplicate in a hashtable (dictionary). That this may lead to an invalid implementation should perhaps somehow be mentioned in the RFC? If it already is, I'd love a pointer to the relevant paragraph.

**Comment by mnot** [comment]
Closing based upon changes above; if they aren't enough / right / clear, please reopen.

**Comment by asbjornu** [comment]
@mnot I think this is a clear improvement. If we can get some traction on #143 as well, implementers would have a much easier job. Thanks!
