### ISSUE TITLE
link attribute registry

### ISSUE THREAD

**Issue by darshakthakore** [mnot/I-D#171]
The use of web-linking has expanded a lot since RFC5988, specifically its usage in CoRE and other IoT ecosystems. For example, [RFC 6690](http://tools.ietf.org/html/rfc6690) adds new attributes ('rt', 'if', 'sz'), [RFC 7641](http://tools.ietf.org/html/rfc7641) adds the 'obs' attribute and various other drafts are adding additional attributes. Seems like a link attribute registry would be useful for ensuring there are no accidental name collisions and also for a place to look for what's already defined.

**Comment by darshakthakore** [comment]
this issue should be labeled rfc5988bis

**Comment by mnot** [comment]
Dup of #36, I think.
