### ISSUE TITLE
"param" instead of "var"

### ISSUE THREAD

**Issue by RubenVerborgh** [mnot/I-D#173]
In related specifications, in particular RFC6570, the term "parameter" (`param`) is used for components of a URI.

**Comment by mnot** [comment]
6570 uses `parameter` most often to talk about syntactic constructs in URIs; `variable` is used to talk about the input to templates, which is what's happening here.

**Comment by mnot** [comment]
Closing; if I've misused these terms somewhere (keeping the above in mind), please reopen or open a new one. Thanks.
