### ISSUE TITLE
Relation to Webapp Manifest

### ISSUE THREAD

**Issue by dret** [mnot/I-D#174]
for the home documents spec, it would be interesting to at least discuss its relation to webapp manifests as specified over at https://github.com/w3c/manifest. there is an extension point in that spec that would allow new properties to be added in a graceful way. if that spec would establish a registry of some kind, these properties could even be established by a different spec and made well-known by registering them. it might be interesting to see what the difference would be between the home document draft as it is now, and a model it would be recast as a webapp manifest with some extension properties.

**Comment by dret** [comment]
created https://github.com/w3c/manifest/issues/452 as an issue for the webapp manifest draft.

**Comment by mnot** [comment]
@marcoscaceres any thoughts? I'm happy to chat, but not sure whether coordination is going to be worth the extra friction on both sides...

**Comment by marcoscaceres** [comment]
[We have a registry](https://github.com/w3c/manifest/wiki/Extensions-Registry) and @dret is in charge of it... so, go nuts and break all the things! :)

**Comment by dret** [comment]
thanks for having a look, @mnot and @marcoscaceres. it was maybe just an odd idea, and thinking of it a bit more, i don't think there's a lot of value in trying to shoehorn one of these formats into the other. i'll go ahead and close this issue.
