### ISSUE TITLE
Flag to indicate partial digest

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#176]
As discussed in #167, we need a flag to indicate whether the digest is partial or complete for the origin.

For discussion: should this be a flag in the frame header, or the payload?

**Comment by kazuho** [comment]
> should this be a flag in the frame header, or the payload?
Would it be better to have the flag in the payload, considering the fact that we _may_ add a field to the payload that modifies the scope of the digest (e.g. the `origin` attribute)?

**Comment by mnot** [comment]
See #177 for updated frame layout. 

I don't have a strong feeling on this. If we put it into the frame, I think we'll end up with something like:

~~~~
+-----------+-------+-------+
| flags (8) | N (5) | P (5) |
+-----------------------------------------------+
|              Digest-Length (24)               |
+-----------------------------------------------+
|              Digest-Value? (*)              ...
+-----------------------------------------------+
~~~~

Which is a bit odd, because (a) there's already a flags field in the frame header, and (b) extensions will go at the bottom, not the top with the flags.

WDYT?

**Comment by kazuho** [comment]
Would it be strange if we define the indicator for a partial digest directly in the format (like shown below) instead of defining `flags`?

Also, shouldn't Digest-Length and Digest-Value be aligned to 8-bit boundary?

If the two are OK to you, how does the following look to you?
```
+--------------+-------------+-------+-------+
| Reserved (5) | Partial (1) | N (5) | P (5) |
+--------------------+-----------------------+
| Digest-Length (24) |
+--------------------++
| Digest-Value? (*) ...
+---------------------+
```

**Comment by mnot** [comment]
Please reopen if you see any issue.
