### ISSUE TITLE
RFC5987(bis) processing on extension attributes

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#180]
Right now, the link header defines _two_ serialisations for extension target attributes, differentiating them with a * on the end of the name (thanks to RFC5987 encoding).

How should this be surfaced in the generic link model? A few possibilities:
1. They're automatically processed and write over the *-less version of the attribute.
2. Both versions are exposed to the consumer; it can pick what to use.
3. Don't allow RFC5987 encoding for extension attributes.

There are downsides to all of them:
1. This could have security implications for some relations, and relations that support more than one occurrence on the link are forced to use one or the other.
2. Now relations have to define whether they support the * version in this serialisation.
3. No i18n in link relations (unless we can assume that the header value is UTF-8).

Next steps:
- [ ] Figure out whether the security implications are real
- [ ] Investigate whether assuming UTF-8 (effectively deprecating 5987, at least for extensions) is a possibility

**Comment by mnot** [comment]
Firefox appears to assume ISO-8859-1 encoding (at least for `title` on `rel=stylesheet`); see:
  http://test.mnot.net/foo/

**Comment by mnot** [comment]
... and that appears to be based upon Link's original use of `quoted-string`, which in turn used `TEXT`. 

However, RFC7230 obsoleted `%x80-FF` in `quoted-string`.

It's tempting to say that at a minimum, extension parameters don't use `quoted-string`, but instead a new ABNF rule that contains UTF-8, not ISO-8859-1. Title might have to stay with RFC5987 encoding for backwards compatibility.

**Comment by asbjornu** [comment]
I'm :+1: for defaulting to UTF-8. Does RFC 7230 and an UTF-8 default mean that there isn't a problem with `*` and encoding, or does that still need to be tackled somehow?

**Comment by mnot** [comment]
@reschke any thoughts?

**Comment by reschke** [comment]
Firefox is consistent in how it treats non-ASCII in quoted-string (the same is true for Content-Disposition, AFAIK). I don't believe that having rules per header field is a good idea.

**Comment by mnot** [comment]
I think spec authors would find it surprising (in a bad way) that someone could inject/override a parameter field value into a header by adding another instance of it suffixed with `*`.

What's not clear is whether that surprise is potentially a vulnerability. However, it feels somewhat similar to HTTP response splitting and the like, especially since the recipient is allowed to fall back to the other form if they don't do 5987 decoding.

@mikewest @rlbmoz any thoughts?

**Comment by reschke** [comment]
"I think spec authors would find it surprising (in a bad way) that someone could inject/override a parameter field value into a header by adding another instance of it suffixed with *."

How is that different from injecting the same parameter without the "*"?

Reminder: parameters are not supposed to repeat; but that might be just folklore (Keith told me that back when RFC5987-to-be mentioned multiple instances of "title*" to provide information in multiple languages).

**Comment by mnot** [comment]
An author can specify exactly one instance of a parameter, first match wins, and still be vulnerable to having it interpreted different by different recipients -- even if the payload is an integer (for example).

**Comment by reschke** [comment]
OK. Approach #2 sounds better then.

**Comment by mnot** [comment]
That's the least desirable option to me; It is really, really nasty to expose a serialisation-specific encoding convention to a consumer. Every link relation that defines parameters that take non-ASCII input would have to talk about this special case.

**Comment by reschke** [comment]
...but then it's at least simple and predictable in that all parameters are treated uniformly.

**Comment by asbjornu** [comment]
Would an update to RFC 5987 (-bis), enforcing parameters to only occur once, help? If so, perhaps that should be tackled first? I do see the value of having multiple `title` parameters in different languages, but localization of parameters is a whole beast of its own, isn't it? Not something that's fully solved by allowing parameters to occur more than once, at least.

**Comment by asbjornu** [comment]
I'd say go for option 3 and figure out a better i18n solution.

**Comment by mnot** [comment]
Talked to @reschke about this a bit in Berlin.

I'm currently leaning towards (1), with a fair chunk of text) and maybe requirements in Security Considerations.

**Comment by mnot** [comment]
Now wondering if it needs the sec considerations.

**Comment by mnot** [comment]
Closing for now.
