### ISSUE TITLE
Decoding

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#184]
As per @martinthomson, we need to specify how to use the digest.

**Comment by mnot** [comment]
Straw-man to start defining the algorithm:

## Querying the Digest for a Value {#querying}

Given:
* `digest-value`, an array of bits
* `URL`, an array of characters
* `ETag`, an array of characters
* `validators`, a boolean

we can determine whether there is a match in the digest using the following algorithm:

1. Read the first 5 bits of `digest-value` as an integer; let `N` be two raised to the power of that value.
2. Read the next 5 bits of `digest-value` as an integer; let `P` be two raised to the power of that value.
3. Let `hash-value` be the result of computing a hash value ({{hash}}).
4. Let `C` be 0.
5. Read '0' bits from `digest-value` until a '1' bit is found; let `Q` bit the number of '0' bits. Discard the '1'.
6. Read log2(`P`) bits from `digest-value` after the '1' as an integer; let `R` be its value.
7. Let `D` be `Q` * `P` + `R`.
8. Increment `C` by `D`.
9. If `C` is equal to `hash-value`, return 'true'.
10. Otherwise, return to step 5 and continue processing; if no match is found before `digest-value` is exhausted, return 'false'.


Ping @kazuho 

_this assumes we factor out the computation of hash to a seperate section_

**Comment by kazuho** [comment]
@mnot Thank you for your effort!

I believe step 4 should start `C` from -1, and step 8 should increment `C` by `D + 1`.  In the encoding process we subtract 1 from the delta (because we do not encode duplicates), and we need to the reverse during the decoding process.

Other than that I do not see any issues.

**Comment by martinthomson** [comment]
At what point are the characters turned into octets?

**Comment by martinthomson** [comment]
Note also that you can stop parsing when `C > hash-value`.

**Comment by mnot** [comment]
> At what point are the characters turned into octets?

That's in {{hash}}.

> Note also that you can stop parsing when C > hash-value.

I think that's an optimisation we can leave up to the reader; this is pseudo-code, after all :)
