### ISSUE TITLE
Relationship between attributes and parameters

### ISSUE THREAD

**Issue by asbjornu** [mnot/I-D#185]
I'm probably just dim, but I don't think RFC 5988 is clear on the difference between "target attributes" and "link parameters". Could a section describing the difference and the relationship between them be added, or at least described to me so I understand the difference? Thanks! :smile:

**Comment by mnot** [comment]
target attributes are on the abstract link model; link parameters are on the concrete syntax of the link header serialisation. 

If there's somewhere where they're used inconsistently, please do point it out.

**Comment by asbjornu** [comment]
@mnot I don't think they're used inconsistently, I just wish that they were discerned more expressively in the specification, because I'm still not sure what:

>target attributes are on the abstract link model; link parameters are on the concrete syntax of the link header serialisation.

actually means. Can you please elaborate, preferably in the specification?
