### ISSUE TITLE
value-less parameters

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#190]
Link parameters are seen in the while without a value; e.g., `rel='preload' crossorigin` in http://w3c.github.io/preload/

**Comment by asbjornu** [comment]
In HTML, value-less attributes are called [boolean attributes](https://www.w3.org/TR/html5/infrastructure.html#boolean-attributes), perhaps rfc5988bis should adopt that and call value-less parameters for "boolean parameters" too?

**Comment by mnot** [comment]
ABNF in 5988 already supports this.

**Comment by mnot** [comment]
No it doesn't (at least now).

**Comment by martinthomson** [comment]
See also `nopush`: https://w3c.github.io/preload/#server-push-http-2
