### ISSUE TITLE
Add service link relation types

### ISSUE THREAD

**Issue by dret** [mnot/I-D#191]
this may be a bit of a long shot, but in particular if the "home" link relation gets added (#41), then what about also adding the two link relations proposed in https://tools.ietf.org/html/draft-wilde-service-link-rel? it's a separate draft now, but i think home documents would be a great home (ha!) for those link relations, making things a little less scattered across a variety of drafts.

**Comment by asbjornu** [comment]
The less RFC's people have to read, the better, imho. While modularity is a good design pattern, I don't think there's much need for that here. So :+1:.

**Comment by mnot** [comment]
I've just sketched in a separate top-level member about the API itself, but am amenable to changes. Will have a read of that and think.

**Comment by dret** [comment]
On 2016-11-22 22:51, Mark Nottingham wrote:
> I've just sketched in a separate top-level member about the API itself,
> but am amenable to changes. Will have a read of that and think.

thanks, and any thoughts/issues/feedback/requirements you might have 
would be very welcome at 
https://github.com/dret/I-D/issues?q=is%3Aopen+is%3Aissue+label%3Aservice-link-rel

**Comment by dret** [comment]
the "API Object" now lists three link types (`author`, `describedBy`, `license`). https://github.com/dret/APIdocumentation/issues/1 has a few more (not all of them existing link relations yet) and generally attempts to look at what additional information might be interesting for some APIs.
`describedBy` is recommended to be used for something where https://tools.ietf.org/html/draft-wilde-service-link-rel recommends `service-desc` and `service-doc`. the idea of the latter is to clearly separate machine- and human-oriented description/documentation.

**Comment by dret** [comment]
https://tools.ietf.org/html/rfc8631 has been published.
