### ISSUE TITLE
Drop URI Template Support

### ISSUE THREAD

**Issue by dret** [mnot/I-D#193]
this is a radical proposal but maybe will make it easier to proceed: i am not sure how many people need and use the descriptive structures for URI templates. these seem to introduce quite a bit of complexity in the draft, and maybe will only be used by a small fraction of users. having attempted describing URI templates myself (https://github.com/dret/I-D/tree/master/Abandoned/link-desc) i tend to think that this is a hard problem to get right, so maybe dropping them would speed up the development of the spec, not really impact many users, and make the spec considerably more simple to read and use?

**Comment by mnot** [comment]
That means that you couldn't use json-home for generative URLs, which seems like a pretty big deal.

**Comment by dret** [comment]
On 2016-07-22 07:21, Mark Nottingham wrote:
> That means that you couldn't use json-home for generative URLs, which
> seems like a pretty big deal.

true. it just seems to me that defining the one description format for 
template variables is not something that anybody so far has successfully 
done. so maybe support templates yes, but stay away from also providing 
any description of the variables?

at least for myself i can safely say that i have tried to come up with 
such a description format for quite a while, and it never seemed to make 
a lot of sense as something to impose on all users of templates.

but then again, the latest draft does not really describe the variables, 
it simply maps the local template names to URIs, assuming that for 
those, there might be some description (that's how i understand the 
mechanism). is that a general mechanism (mapping template-local vars to 
URIs) that people have been asking for? i am really just curious here as 
to where a good 80/20 balance is.

**Comment by mnot** [comment]
Hm. Unknown for now -- would have to look at the proto-implementations to see what they're doing here (if at all). 

More than anything, I just wanted to give the vars unique, global names. I agree that may not be enough motivation.

**Comment by dret** [comment]
On 2016-11-03 23:05, Mark Nottingham wrote:
> Hm. Unknown for now -- would have to look at the proto-implementations
> to see what they're doing here (if at all).

understood. and yes, it would be good to see how much URI template 
support is implemented and needed. without having any data i would guess 
that the vast majority of use cases are not using them. but that's 
nothing but a guess.

> More than anything, I just wanted to give the vars unique, global names.
> I agree that may not be enough motivation.

understood as well. and i think that's a very useful thing to do, i 
toyed around with something similar. it does make implementing support 
for home documents a bit harder, since URI template parsers may not be 
that universally available.

**Comment by mnot** [comment]
https://github.com/uri-templates/uritemplate-spec/wiki/Implementations

**Comment by mnot** [comment]
Closing for now, feel free to reopen if it's bugging you still.
