### ISSUE TITLE
Home implementation

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#197]
for tracking:
  https://apidemo.w3ctag.org

cc @plinss

**Comment by plinss** [comment]
Also:
https://api.csswg.org/shepherd

**Comment by plinss** [comment]
Client implementation (used by Bikeshed):
https://github.com/plinss/apiclient

**Comment by mnot** [comment]
https://github.com/krainboltgreene/hsdk.js

e.g., https://github.com/krainboltgreene/hsdk.js/blob/core/example/client.js

**Comment by mnot** [comment]
Now tracking here:
  https://github.com/mnot/I-D/wiki/json-home
