### ISSUE TITLE
Different kinds of link relation types

### ISSUE THREAD

**Issue by aef** [mnot/I-D#198]
Since draft 4 you seem to have dropped any mention of classic link relation types and instead use URIs of the `tag` scheme now. How do these relate to the link relation types registered in the [IANA link relation type registry](http://www.iana.org/assignments/link-relations/link-relations.xhtml) and those classic custom link relation types that were defined as simple URIs of `http` scheme? Is there some kind of mapping necessary, or can all kinds be used in a JSON home document? If so, i think a mention and some examples about this would be very helpful.

**Comment by mnot** [comment]
Don't read too much into the examples -- I didn't use registered relation types because there wasn't a good example of one (and I suspect most APIs are going to be using api-specific ones).

Generally agree that the examples / supporting prose need more clarity though. Thanks!
