### ISSUE TITLE
Links to external sites (aka absolute URIs or network-path-references) in JSON home

### ISSUE THREAD

**Issue by aef** [mnot/I-D#199]
It seems that providing links to external sites (URIs that are not references to the context URI of the home document) is disallowed in JSON home.

Is that really intentional? Why is that so?

For example, I would like to use a home document in one service to provide URIs and URI templates for its publicly exposed resources. Resources that are potentially mostly accessed by human users through a browser in the end. Another service could ask the first service for those URIs to display these to its human clients, so they can use the resources provided by the other service.

A problem occurs now because all services are integrated into one single site for the human users. But each service owns his own site which is not publicly accessible. The services use these private sites to talk to each other. Providing links to the public site from a home document on one of the private sites seems to be disallowed by the current drafts.

Is this a consequence of JSON home being tailored specifically for "non-browser" clients? If so, wouldn't it be a closer to the idea of REST to include all kinds of clients using the same URIs (but specific representations)? And shouldn't links to any site be allowed? If links to other sites are not allowed, is it still a "web" technology?

**Comment by aef** [comment]
Another example would be providing links to image resources on one site, but the images themselves are provided by an external CDN site.

**Comment by mnot** [comment]
What text in the spec makes you believe this?

**Comment by aef** [comment]
In draft 4 it is in section 3 "Resource Objects" saying
> In both forms, the links that "href" and "href-template" refer to are URI-references [RFC3986] hose base URI is that of the JSON Home Document itself.

**Comment by aef** [comment]
So this wasn't your intention. I guess I would have never thought about it meaning this if it said that "In case it is a relative reference, the base URI is that of the JSON Home Document itself."

**Comment by aef** [comment]
Just to make it perfectly clear for everyone: You did not intend to limit linking to external sites in JSON home documents, right?

**Comment by mnot** [comment]
Correct.
