### ISSUE TITLE
Sets of link relation types

### ISSUE THREAD

**Issue by aef** [mnot/I-D#200]
At least in HTML and the Link headers described in RFC 5988 it is possible to publish a link carrying a set of link relation types. Examples would be `rel="stylesheet alternate"` or `rel="shortcut icon"` (I am aware that there are issues about the meaning and formal specification of the `shortcut` link relation type). The current draft doesn't seem to explicitly describe how to handle such sets.

Combining commonly known link relation types to form a meaningful predicate for a resource seems like a very good idea compared to defining new, complex link relation types for all kinds of resources. The former way at least theoretically allows clients with a basic knowledge of common link relation types to deduct the meaning of a resource (even when the meaning needs to be combined somehow), instead of requiring established knowledge of custom link relation types in use at a site before the client may know what a link is all about.

So have relation type sets been left out intentionally? If not, how are we supposed to handle these? Is there a specific lexical order expected so the JSON hash table based lookup doesn't fail if a set is given in a different order than was originally expected by a client?

**Comment by mnot** [comment]
From 5988 Section 4:

> Relation types SHOULD NOT infer any additional semantics based upon  the presence or absence of another link relation type, or its own cardinality of occurrence.  An exception to this is the combination of the "alternate" and "stylesheet" registered relation types, which has special meaning in HTML4 for historical reasons.

**Comment by aef** [comment]
I must have missed that part. Thank you very much for your clarification.
