### ISSUE TITLE
Performance of Cache Digests

### ISSUE THREAD

**Issue by cbas** [mnot/I-D#204]
Just implemented the spec (which was a lovely exercise) and had some thoughts on how to improve performance of the CD algorithm. Apologies if I misunderstood some parts of the spec or the authors' intentions.

### De-dupe URLs before hashing them
- Wastes time sorting and skipping through the list in a later stage.
- Inflates value of `N`, needlessly increasing size of the entire digest.

### Trim URL origin
- Every URL has identical origin. Hashing this repetitive data is wasted effort.

### SHA256 is overkill
- Use a fingerprinting algorithm for better performance. See: https://github.com/rurban/smhasher
- Spec limits `hashValue` to 62 bits so why generate 256 bits? Lots of algos return 64 bits which minimises waste.

**Comment by mnot** [comment]
See - https://github.com/httpwg/http-extensions

**Comment by cbas** [comment]
Thanks @mnot 👍

I see interesting discussion on the hashing algo choice in https://github.com/httpwg/http-extensions/issues/228 It would perhaps be useful to run some benchmarks on real( world|istic) data to check whether hashing performance is really an issue. Will see what I can dig up and share any findings.
