### ISSUE TITLE
Typo in draft-kazuho-h2-cache-digest-01

### ISSUE THREAD

**Issue by cbas** [mnot/I-D#205]
#### 2.2.1.  Querying the Digest for a Value
```
[...]
   5.   Read '0' bits from "digest-value" until a '1' bit is found; let
        "Q" bit the number of '0' bits.  Discard the '1'.
```

Should be:
> let "Q" **be** the number of '0' bits.

**Comment by mnot** [comment]
Wrong repo - this has moved to https://github.com/httpwg/http-extensions
