### ISSUE TITLE
Key: support "OR" operator

### ISSUE THREAD

**Issue by igrigorik** [mnot/I-D#21]
> a cache that implements the Key header field MUST NOT use a stored response unless all of the selecting header fields nominated by the Key header field match in both the original request (i.e., that associated with the stored response) and the presented request.

Above behavior dictates "AND" operation on all of the Key parameters. What about "OR"? For example, what if I wanted the response to be cached for multiple UA's - e.g. Android, iPhone. 

> Key: user-agent;s="Android";s="iPhone"  (Android AND iPhone)
> Key: user-agent;s="Android";o;s="iPhone" (Android OR iPhone)

First example is an implicit AND, and wouldn't be satisfied for any UA.. Whereas, what we're actually after is the second case, where we want the cache to serve the response to multiple different UA's. Q: is there a reason why "OR" is omitted in current spec? Could / should we add a parameter ("o" in above example) to support this?

**Comment by mnot** [comment]
Moving discussion to https://github.com/httpwg/http-extensions/issues/104
