### ISSUE TITLE
Suggestion: use an existing API spec format for the API description

### ISSUE THREAD

**Issue by ivan-novakov** [mnot/I-D#210]
Having a standard for API "home" is not a bad idea really. But I would reconsider, whether not to use an existing API description format like Swagger, API Blueprint, RAML, etc.

The advantage is clear:
- no need to reinvent the wheel
- much larger community
- existing ecosystem of tools & parsers

In fact, this standard may support various API specification formats. The client application can then choose the right one through content negotiation.

**Comment by mnot** [comment]
The use cases aren't the same. The main target here is defining extensible, evolvable, standard HTTP APIs (e.g., by IETF Working Groups). Swagger et al are much more focused on delivering one-off, single instance APIs a la Twitter et al. 

Like @dret said in another issue just now, that doesn't mean that you can't link to swagger et al. from home doc.
