### ISSUE TITLE
Nit for Section 4

### ISSUE THREAD

**Issue by mamund** [mnot/I-D#221]
_(for 5988bis)_

I found myself internally translating the example sentences for "copyright" and "service" link relation types found in Section 4 into the template language supplied in Section 3.  It might be a good idea to provide the examples in the same template language to make this a bit easier to grok.

so..

> For example, a link with the relation type “copyright” indicates that the resource identified by the link target is a statement of the copyright terms applying to the current link context.

would be:

> For example, a link with the relation type “copyright” indicates that the current link context has a copyright resource at the link target.  

This is just a nit.

**Comment by asbjornu** [comment]
I find the rewritten paragraph to be easier to read and understand, so 👍  from me.
