### ISSUE TITLE
Clarify Character Encoding Attributes for 5988bis Section 6.4

### ISSUE THREAD

**Issue by mamund** [mnot/I-D#223]
This section covers use of the "title" and "title*" attributes. However, Section 5 says:

> The names of target attributes SHOULD conform to the token rule, but SHOULD NOT include any of the characters “%”, “’” or “*”, for portability across serializations

And Section 6.4.2 goes on to help parsers deal with the difference between "example" and "example*".  It's not clear to me when reading this whether it is also giving instructions on how to properly _create_ new 5987-style attributes or if this section (6.4.2) is only discussing the parsing of existing 5987-style attributes.

If we don't want authors creating new 5987-style attributes, it might be helpful to repeat that here or to point back to Section 5's admonition.

**Comment by mnot** [comment]
To be clear -- `title` and `title*`, when serialised in a Link header, are *parameters* -- the spec should use that terminology consistently.

*Attributes* are in the abstract model (defined in Section 3); *parameters* are specific to the header serialisation, as defined in Section 6. If you find anywhere where these terms are used in a way that's inconsistent with this explanation, I'd love to hear about it.

That aside, 6.4.2 is pretty explicit about allowing the use of 5987-style parameters, when attributes want it; can you suggest a clarification?
