### ISSUE TITLE
Explain "title" I18N in "Internationalization" section

### ISSUE THREAD

**Issue by dret** [mnot/I-D#228]
maybe it would be helpful to explain how non-ASCII characters are supposed to be handled (in particular in text strings such as the `title`/`title*` parameters). currently https://tools.ietf.org/html/draft-nottingham-rfc5988bis#section-6 only talks about IRIs and URIs. maybe some text about general character encoding considerations would be helpful.

**Comment by mnot** [comment]
See <https://mnot.github.io/I-D/rfc5988bis/#extension-attributes>.

**Comment by dret** [comment]
thanks for the pointer. concretely, what about linking to this section (or 5987bis directly) with a brief statement about how internationalization of parameter values is working?

> For any non-ASCII values in attribute values, this specification uses (for title/title*) or suggests to use (for extension attributes) the encoding defined in RFC 5987bis, which uses a naming convention combined with mandatory character encoding and optional language information, followed by escaped attribute values.

**Comment by mnot** [comment]
Ah, missed this, sorry.
