### ISSUE TITLE
Alternate approach

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#229]
_Considered earlier and rejected_

By definition, the Internet is a "network of networks." From an architectural standpoint, the Internet has the most utility when it has the greatest network effect, by involving the greatest number of networks, nodes and perhaps most critically, people.

This is shown by the increasing impact of the Internet as adoption rates have risen in many societies. In many places, the Internet is now critical to physical infrastructure, the economy, education, culture, and civil society.

To safeguard this utility, those developing Internet protocols need to consider impact on the breadth of adoption.

Most decisions we make are well-aligned with this; we do not want to deploy protocols that do not get used. However, from time to time, there is a proposal made to the IETF that meets an immediate need, but endangers the longer-term utility of the protocol in question, or even the Internet itself.

In particular, when a protocol (or protocol extension) can be perceived to prioritise the needs of a third party over the end users of the Internet, this can erode trust in the Internet overall -- thereby reducing the utility of the Internet.

For example, network operators often express a desire to be able to man-in-the-middle encrypted protocols such as HTTPS for operational reasons, or to introduce new services. Doing so would erode end-user trust in the protocol, since HTTPS is explicitly end-to-end encrypted.

This is a "tragedy of the commons" -- satisfying the immediate needs of some parties at the expense of the overall value of the community is not a sustainable model, and must be guarded against.

Therefore, Internet Protocols MUST prioritise the needs of end users of the Internet over all other parties.

## Application

By "end users", we mean non-technical users whose activities our protocols are designed to support. Thus, the end user of a protocol to manage routers is not a router administrator; it is the people using the network that the router operates within.

This does not mean that the IETF community has any specific insight into what is "good for end users"; as always, we will need to interact with the greater Internet community and apply our process to help us make decisions, deploy our protocols, and ultimately determine their success or failure.

It does mean that when a proposed solution to a problem has a benefit to some other party at the identified expense of end users, we will find a different solution or find another way to frame the problem.

In particular, some choices we make might unavoidably reduce the availability of the Internet to a set of users. For example, requiring encryption in a protocol might prevent its use in some legal contexts. Likewise, refusing to define performance enhancing proxies for a protocol might preclude the use of that protocol by...

**Comment by akuckartz** [comment]
:+1:
