### ISSUE TITLE
Problem Details in HTTP Link Header

### ISSUE THREAD

**Issue by asbjornu** [mnot/I-D#230]
Just a random thought I had now while setting up status code logging for a few APIs: It would be awesome if the problem detail properties from RFC 7807 could be expressed in a `Link` header with an appropriate `rel` value. Something like:

```http
Link: <https://example.com/probs/out-of-credit>; rel="problem-type"; title="You do not have enough credit."; detail="Your current balance is 30, but that costs 50."; instance="/account/12345/msgs/abc"
```

Perhaps it's a bit of a stretch to include all properties from RFC 7807, but `title` and the `problem-type` link relation would be very useful. Is an RFC 7807bis planned?

/cc @dret

**Comment by dret** [comment]
On 2017-06-30 04:27, Asbjørn Ulsberg wrote:
> Just a random thought I had now while setting up status code logging for
> a few APIs: It would be awesome if the problem detail properties from
> RFC 7807 could be expressed in a |Link| header with an appropriate |rel|
> value. Something like:
>
> Link: <https://example.com/probs/out-of-credit>; rel="problem-type";
> title="You do not have enough credit."; detail="Your current balance is
> 30, but that costs 50."; instance="/account/12345/msgs/abc"
>
> Perhaps it's a bit of a stretch to include all properties from RFC 7807,
> but |title| and the |problem-type| link relation would be very useful.

maybe there's a bit of an imbalance here between a RDFish world view, 
and link relations a la RFC 5988. exposing every property of some data 
model as link relations is something that looks more like a published 
RDF vocabulary, and not so much link relations where the goal is to 
provide relations that make sense as navigable hypermedia controls.

there was some effort to define an RDF version of HTTP problem a little 
while ago, but after an initial "that would be nice to have" phase the 
effort stalled, and i have moved it to my abandoned efforts space:

https://github.com/dret/I-D/tree/master/Abandoned/http-problem-rdf

> Is an RFC 7807bis planned?

i don't think so. but of course if here is enough momentum to work on an 
updated version, that i always a possibility.

**Comment by asbjornu** [comment]
While a JSON-LD `@context` for `application/problem+json` would be neat, it does not solve the specific use case of having the `type` URI available in an HTTP header so it can be logged alongside the HTTP status code.

I did state that exposing all of the properties would be a stretch. That's not something I need either; I just thought that since `title` already exist as a `Link` target attribute, we might as well use it to convey RFC 7807's `title`.

I don't think the link relation `problem-type` warrants a revision to RFC 7807, so perhaps it can be put up as a separate I-D?

**Comment by dret** [comment]
On 2017-07-01 16:22, Asbjørn Ulsberg wrote:
> I don't think the link relation |problem-type| warrants a revision to 
> RFC 7807, so perhaps it can be put up as a separate I-D?

that's something you can easily do yourself, if you think it will be 
useful and would like to get such a link relation registered. if you're 
looking for a starting point, 
https://github.com/dret/I-D/tree/master/service-link-rel might be 
useful. feel free to reuse/adapt in any shape or form that's helpful.
