### ISSUE TITLE
Forbid 'digest' with HTTP as well

### ISSUE THREAD

**Issue by martinthomson** [mnot/I-D#234]
Digest authentication is laughably weak; anything that uses it over HTTP is asking for trouble.

**Comment by mnot** [comment]
Which spec was this for?

Also, do you have a ref for vulnerabilities? Its problems signing headers is well-understood; what else?

**Comment by martinthomson** [comment]
bcp56bis

There should be plenty.  Dictionary attacks on low-entropy secrets are trivial when the hash is as cheap as MD5.  I found RFC 7616, which explains the limitations in some detail.

**Comment by mnot** [comment]
ah, that's right -- we talked about moving past md5 on that, but never did it.

**Comment by mnot** [comment]
in httpwg repo now
