### ISSUE TITLE
JSON Home media type

### ISSUE THREAD

**Issue by asbjornu** [mnot/I-D#237]
I see that the draft uses `application/json-home` as its media type. Shouldn't it be `application/home+json`? Afaik, `application/home` is still an unregistered media type?

Also, what's the status on the draft? Any ideas of if and when it will become an RFC?

**Comment by mnot** [comment]
See https://github.com/mnot/I-D/issues/172

**Comment by asbjornu** [comment]
Ah. My memory is really not my strongest asset. 😕

**Comment by mnot** [comment]
I know that feeling :)
