### ISSUE TITLE
serialization rules for repeated link parameters

### ISSUE THREAD

**Issue by dret** [mnot/I-D#239]
the current RFC 5988bis draft has the following example:

```
<http://example.org/>; rel="start http://example.net/relation/other"
```

is it correct to assume that this is equivalent to the following:

```
<http://example.org/>; rel="start", <http://example.org/>; rel="http://example.net/relation/other"
```

as well as the following:

```
<http://example.org/>; rel="start"; rel="http://example.net/relation/other"
```

the reason is to figure out if there is a general model of how multiple occurrences of the same link parameter are to be processed. the reason for the question is that @hvdsomp and i are working on a JSON version (as discussed elsewhere previously). our current approach uses

```json
[ { "href" : "http://example.org/" , "rel" : "start" } ]
```

but that won't work if we need to support repeating link attributes (it would be valid JSON but very badly designed JSON). the question we therefore have is how exactly repeated link parameters are defined. and can we leverage this definition to support our goal of having a simple JSON representation as shown above?

**Comment by hvdsomp** [comment]
Good observation. Can we address this by stating that an approach must be taken whereby parameters are not repeated, e.g.:

[ { "href" : "http://example.org/" , "rel" : "start http://example.net/relation/other" } ]

or:

[ { "href" : "http://example.org/" , "rel" : "start" } ,
  { "href" : "http://example.org/" , "rel" : "http://example.net/relation/other" } ]

**Comment by dret** [comment]
On 2017-08-03 01:59, Herbert Van de Sompel wrote:
> Good observation. Can we address this by stating that an approach must 
> be taken whereby parameters are not repeated, e.g.:

my guess is since this hasn't been disallowed by RFC 5988, it might be 
hard to add such a constraint now. i have no idea how often repeated 
link parameters occur in link headers in the wild.

my main issue here is to understand the exact abstract model of the 
current draft, so that we can try to represent it as well as possible in 
the JSON representation, and that we can clearly state how the native 
and the JSON representation relate.

**Comment by hvdsomp** [comment]
I would like to note that these:

`<http://example.org/>; rel="start", <http://example.org/>; rel="http://example.net/relation/other"`

`<http://example.org/>; rel="start"; rel="http://example.net/relation/other"`

`<http://example.org/>; rel="start http://example.net/relation/other"`

express two links as per the abstract model of RFC5988bis: a link has link context, link relation type, link target, optional target attributes. 

All examples above use a shortcut allowed by the syntax defined in RFC5988bis, in that they don't express the anchor. I agree that this is a shortcut that most likely must also be supported in JSON; and can be supported because the link context can be derived from the interaction anyhow. 

The second and third example show additional shortcuts allowed by the serialization defined in RFC5988bis. The first example does not use those shortcuts.
* The shortcut used in the second example would cause problems in JSON because the "rel" member would have to be repeated to support it. Which is a no go. 
* The shortcut in the third example could be supported in JSON, as far as I can tell. But I am uncomfortable with it because it creates a situation in which a space for one value (the value of rel) must be interpreted in another way then a space for other values (say the value of title). I can't say I find that aestethicgally pleasing.

In essence, what I am trying to suggest is that I do not think that, because RFC5988bis defines a serialization that supports certain shortcuts, the JSON serialization must support them too. The JSON serialization is a serialization of the abstract link model of RFC5899bis. It is not a transformation of the syntax of RFC5988bis into JSON. I do agree, however that moving back/forth between these serializations should be possible.

And also a question: Are there examples where target attributes (eg title, type, ...) are repeated on links expressed as RFC5988bis?

**Comment by dret** [comment]
On 2017-08-04 02:33, Herbert Van de Sompel wrote:
> The second and third example show additional shortcuts allowed by the 
> serialization defined in RFC5988bis. The first example does not use 
> those shortcuts.
> 
>   * The shortcut used in the second example would cause problems in JSON
>     because the "rel" member would have to be repeated to support it.
>     Which is a no go.

afaict, RFC 5988bis explicitly allows repeated target attributes. if a 
serialization of the abstract model disallows this feature, then at 
least it should say so, and specify how instances of the abstract model 
are supposed to be serialized. there probably are three major options:

- specify that the first occurrence is used and that subsequent 
occurrences must be ignored. for the example used in this issue, this 
would actually drop a link.

- specify that multiple occurrences must be stringified into one value. 
this is what the example presented here is using. the downside is that 
there probably is not universal model how this works (for "rel" values 
are space-separated, but other target attributes could define other 
methods such as comma or semicolon separation).

- specify that multiple target attributes must be folded into one JSON 
member with multiple values, possibly an array. this is the best 
structural option but awkward because not target attributes can be 
either strings or arrays or strings.

>   * The shortcut in the third example could be supported in JSON, as far
>     as I can tell. But I am uncomfortable with it because it creates a
>     situation in which a space for one value (the value of rel) must be
>     interpreted in another way then a space for other values (say the
>     value of title). I can't say I find that aestethicgally pleasing.

same here. but note that this variant is explicitly allowed in the 
draft. that's because pretty much all representations of types links 
allow this method of whitespace-separated multiple relation types.

> In essence, what I am trying to suggest is that I do not think that, 
> because RFC5988bis defines a serialization that supports certain 
> shortcuts, the JSON serialization must support them too. The JSON 
> serialization is a serialization of the abstract link model of 
> RFC5899bis. It is not a transformation of the syntax of RFC5988bis into 
> JSON. I do agree, however that moving back/forth between these 
> serializations should be possible.

i think my main question to @mnot is: is the second option (multiple 
"rel" on the same link) allowed or disallowed by the draft? but actually 
now that i am reading through all of it (rtfd!), i see that it is 
explicitly disallowed. which is good because that takes the second 
example off the table. but there still are cases where repeated target 
attributes are allowed (see below).

> And also a question: Are there examples where target attributes (eg 
> title, type, ...) are repeated on links expressed as RFC5988bis?

afaict, "hreflang" explicitly allows repetition. repetitions are not 
explicitly disallowed for "anchor", but that's probably just an 
oversight as it does not make a lot of sense, semantically.

for "hreflang", there actually is the interesting case that we cannot 
"fold" multiple occurrences into one stringified value, because 
"hreflang" does not allow multiple language tags in one target attribite 
value. which gives us an example where we have to decide if/how we want 
to support representing multiple hreflang values on one link value in 
the JSON representation. @mnot, any opinion on that one?

**Comment by hvdsomp** [comment]
After another reading of 5899bis, I think I can summarize the "repeatable" issue as follows:
- of all the target attributes defined by RFC5988bis, hreflang is the only one that is repeatable
- extensions attributes might be repeatable; it's up to those who define them to specify whether they are or not. the thing is they can be.

So, whichever way, we do need a solution for repeatable target attributes.

Note, however, that relation type (serialized as "rel" is not a target attribute). The model for Links clearly separates link relation type from target attributes:

`In this specification, a link is a typed connection between two
   resources, and is comprised of: a _link context_, a _link relation type_ (Section 2.1), a _link target_, and optionally, _target attributes_ (Section 2.2). A link can be viewed as a statement of the form "_link context_ has a _link relation type_ resource at _link target_, which has _target  attributes_".`

The confusing thing is that the link-value ABNF construction rules do merge link relation type and target attributes. As a result of that, the spec does not really make it crispy clear that "rel" is mandatory. It does state:

`The "rel" parameter MUST NOT appear more than once in a given link-value; occurrences after the first MUST be ignored by parsers.`

which does not say there MUST be one "rel". But the model above is clear with that regard.

**Comment by dret** [comment]
On 2017-08-07 01:48, Herbert Van de Sompel wrote:
> The confusing thing is that the link-value ABNF construction rules do 
> merge link relation type and target attributes. As a result of that, the 
> spec does not really make it crispy clear that "rel" is mandatory. It 
> does state:
> 
> |The "rel" parameter MUST NOT appear more than once in a given 
> link-value; occurrences after the first MUST be ignored by parsers.|
> 
> which does not say there MUST be one "rel". But the model above is clear 
> with that regard.

this sounds reasonable. since the statement about "rel" does include 
language about cardinality, it seems as if also stating that there MUST 
be at least one "rel" value would improve the spec language.

**Comment by mnot** [comment]
I think I can do that.

**Comment by dret** [comment]
thanks. https://github.com/mnot/I-D/pull/244 might do the trick.
