### ISSUE TITLE
clarify relationship between "Target Attribute" and link-param

### ISSUE THREAD

**Issue by dret** [mnot/I-D#240]
the current RFC 5988bis draft defines "Target Attribute" and uses this term in the spec language, but the syntax definition then uses `link-params` and the current draft says 'This specification defines the link-params "rel", "anchor", "rev", "hreflang", "media", "title", "title*", and "type"; see Section 3.2, Section 3.3 and Section 3.4.'
what is the relationship between "Target Attribute" and "Link Parameter"? again, the context for this nitpicking is @hvdsomp's and my attempt to come up with a good JSON representation of the RFC 5988bis link model.

**Comment by asbjornu** [comment]
I touched on the same issue in #185.

**Comment by dret** [comment]
On 2017-08-03 04:03, Asbjørn Ulsberg wrote:
> I touched on the same issue in #185 

interesting. i had the same problem understanding the terminology, and 
it seems to me that there still are confusing usages of the terms. for 
example, the current draft says:

'This specification defines the link-params "rel", "anchor", "rev", 
"hreflang", "media", "title", "title*", and "type";'

but that really talks about target attributes i suppose, because what's 
defined are the abstract concepts (which then of course get serialized, 
but that's a different issue).

asked differently: what is the benefit of introducing and using these 
different terms?

**Comment by mnot** [comment]
Target attributes are in the abstract model, link parameters are in the http header serialisation.

**Comment by dret** [comment]
thanks for the clarification. but: wouldn't it then be the case that the spec *"defines target attributes"* (which then get serialized as link parameters) instead of the spec *"defining link parameters"*?

**Comment by mnot** [comment]
It says:

> Target attributes are serialised in the Link header field as parameters (see {{RFC7231}}, Section 3.1.1.1 for the definition of their syntax).

Can you suggest clarifications?

**Comment by dret** [comment]
that part reads fine to me. as mentioned above, it's the 'This specification defines the link-params "rel", "anchor", "rev", "hreflang", "media", "title", "title*", and "type";' part that could be tweaked. afaict, link parameters are an serialization issue and are used to serialize target attributes as well as "rel", "anchor", "rev". so maybe:

> This specification establishes the link-params "rel", "anchor", and "rev" (which are part of the general link model), as well as "hreflang", "media", "title", "title*", and "type" (which are the target attributes defined by this specification)

but then again on closer reading the spec says that there is no such thing as abstract target attributes defined by it, and that "hreflang", "media", "title", "title*", and "type" are instead defined for the header serialization only. but that probably doesn't change the fact that "hreflang", "media", "title", "title*", and "type" indeed are defined as target attributes, and simply are serialized as link parameters.

**Comment by mnot** [comment]
How about:

> This specification establishes the link-params "rel", "anchor", and "rev" (which are part of the general link model), as well as "hreflang", "media", "title", "title*", and "type" (which map to target attributes)

?

**Comment by dret** [comment]
On 2017-08-11 12:28, Mark Nottingham wrote:
>     This specification establishes the link-params "rel", "anchor", and
>     "rev" (which are part of the general link model), as well as
>     "hreflang", "media", "title", "title*", and "type" (which map to
>     target attributes)

This specification establishes the link-params "rel", "anchor", and 
"rev" (which are part of the general link model), as well as "hreflang", 
"media", "title", "title*", and "type" (which are target attributes 
defined by the Link header serialization).
