### ISSUE TITLE
check/align JSON representation of RFC 5988bis link sets

### ISSUE THREAD

**Issue by dret** [mnot/I-D#241]
https://tools.ietf.org/html/draft-wilde-linkset is a new draft @hvdsomp and i have published today. as discussed previously, it defines a JSON-based representation of RFC 5988bis link sets. it would be great to get some feedback about the proposed JSON representation, so that we can make sure that it is as faithful to the RFC 5988bis model as possible, but still is a JSON format that people might use because it easy to understand and use.

**Comment by mnot** [comment]
OK, but this isn't an issue on this spec.
