### ISSUE TITLE
mention JSON representation in RFC 5988bis draft

### ISSUE THREAD

**Issue by dret** [mnot/I-D#242]
it would be great if @hvdsomp's and my draft https://tools.ietf.org/html/draft-wilde-linkset could be mentioned in the sections about target attributes and link parameters. as discussed in #240, these concepts are about the abstract data model and the native serialization.
it would be great if people defining new target attributes would be made aware of the fact that there are alternative serializations, so that they could take into account how their target attributes are working for these. for example, in the current draft (-00), target parameters can not be repeated (because of JSON limitations), meaning that any target attribute that is defined to be repeatable cannot be always serialized in the JSON representation.

**Comment by mnot** [comment]
Too late for this, it's already at the IESG.
