### ISSUE TITLE
HTTP OPTIONS for JSON HOME ?

### ISSUE THREAD

**Issue by vasilakisfil** [mnot/I-D#243]
Just curious: Wouldn't be a good idea to use HTTP OPTIONS to figure out the capabilities of the API through JSON Home?

> The OPTIONS method requests information about the communication
> options available for the target resource, at either the origin
> server or an intervening intermediary.  This method allows a client
> to determine the options and/or requirements associated with a
> resource, or the capabilities of a server, without implying a
> resource action.
>
> --- [RFC 7231](https://tools.ietf.org/html/rfc7231)
>

**Comment by mnot** [comment]
https://www.mnot.net/blog/2012/10/29/NO_OPTIONS

**Comment by vasilakisfil** [comment]
Thanks for pointing out. I think the only valid argument in this blog post is the requirement set by the same RFC that options should not be cachable (hadn't seen that). I think clients should have already fixed the HTTP OPTIONS implementation, and browser inability to send OPTIONS is true but we don't care for JSON Home.

I don't see any reason why options should not be cached, do you know this restriction was added in HTTP spec ?
