### ISSUE TITLE
Privacy considerations

### ISSUE THREAD

**Issue by lknik** [mnot/I-D#246]
The otherwise well-designed document "Reserving the 418 HTTP Status Code" could benefit from a modern shakeup, such us the inclusion of privacy considerations - which is becoming the standard in itself. 

Not much can be said about this particularly short spec. But one point could be to consider whether additional status code isn't potentially (1) increasing the fingerprinting surface; and/or (2) placing some HTCPCP devices at the risk of profiling (disclosure of preferences, maybe even system settings) - although this particular point may be more related to the RFC2324 itself. Though protocol design in '90s looked perhaps a bit differently than today. It might be a worthy opportunity to move forward. Yes, I realize it's not 1st, nor the 4th.

**Comment by mnot** [comment]
Don't think that's in scope for this, but thanks for thinking about privacy!
