### ISSUE TITLE
RFC5988bis - Need clarification on `parameter_value` decode failure

### ISSUE THREAD

**Issue by uhhhh2** [mnot/I-D#250]
In Appendix B.3 "Parsing Parameters", if `parameter_name` ends in `*`, the `parameter_value` is to be decoded according to [RFC 5987bis](https://tools.ietf.org/html/draft-ietf-httpbis-rfc5987bis-05) (now [RFC 8187](https://tools.ietf.org/html/rfc8187)). If this decode operation fails, should the `parameter_value` be set to:

1.  The `parameter_value` before the RFC 5987bis/RFC 8187 decoding attempt
2.  The empty string
3.  Something else

**Comment by mnot** [comment]
Good question.

My instinct would be to remove the star-parameter, and allow it to fall back to the ASCII version of the parameter.

@reschke is there any best practice here?

**Comment by reschke** [comment]
That sounds like a good choice.

**Comment by mnot** [comment]
@uhhhh2 the current text is:

~~~
            5.  If the last character of parameter_name is an asterisk
                ("*"), decode parameter_value according to [RFC8187].
                Continue processing input if an unrecoverable error is
                encountered.
~~~

What's ambiguous about that?

**Comment by mnot** [comment]
Closing; please comment (ASAP, as it's about to be published) if you think this is still an issue.
