### ISSUE TITLE
relation to servmeta and wether "API metadata" should be embedded or outsourced

### ISSUE THREAD

**Issue by dret** [mnot/I-D#254]
as mentioned in https://github.com/dret/servmeta/issues/5, the servmeta format (https://github.com/dret/servmeta/blob/master/format.md) does something very similar to the proposed "API object". it might be interesting to look at overlaps (and the current format definition lists a number of additional possible link relation to be used).
one goal of servmeta was to have a general format for service metadata. this metadata could then link to a variety of resources, such as `home` (https://github.com/mnot/I-D/issues/41) and others. `service-meta` (https://tools.ietf.org/html/draft-wilde-service-link-rel-04#section-4.3) then can be used to discover the initial metadata, with more resources being linked from there.

**Comment by mnot** [comment]
Seems reasonable...

**Comment by dret** [comment]
i'd say that `servmeta` is probably abandoned by now. if you think otherwise, @mamund, please reopen, but otherwise we can safely close this one.
