### ISSUE TITLE
Can we require it for all new headers

### ISSUE THREAD

**Issue by annevk** [mnot/I-D#259]
Context: https://mnot.github.io/I-D/structured-headers/

My hope was that we could evolve header value parsing by having a fixed "legacy list" of HTTP headers whose values need to be parsed using a set of legacy algorithms, specific to those headers and that all new headers could be parsed using the same parser. That would also enable generic typed APIs, rather than APIs that have to know the intricacies of each header name.

I think that was also @mikewest's goal with JSON header values.

(The other hope I had was that we could first get implementations fully aligned on existing header value parsers, including error handling, and maybe draw inspiration from that for the new syntax. Code reuse seems preferable over new bugs.)

**Comment by mnot** [comment]
Individual standards bodies can, of course, whether that's IETF, W3C or WHATWG.

Doing it for *all* headers is harder, but it might be possible to "tilt the table" a bit to encourage this.

**Comment by mikewest** [comment]
I would like for us to have some agreement about how we should do headers going forward, so I'm very much on @annevk's page with regard to new things. We should agree on something. Maybe it's this thing! Maybe it's JSON! Maybe it's a binary format! I have opinions, but at the end of the day, I'll live with whatever we can get sufficient consensus on.

For old headers, I'm on board with minor compatibility tweaks where implementations currently diverge, but I don't think it would be worth anyone's time to try to move them wholesale to a new format. *shrug* To that end, a legacy list of legacy algorithms makes sense to me.

**Comment by mnot** [comment]
FWIW I think your statement about legacy headers is the consensus position, roughly; we don't want to reinvent the world wholesale, although we *might* go and backport things selectively where there's a (tremendous amount of) will.

**Comment by annevk** [comment]
I feel like you closed this without some kind of conclusion @mnot. I never meant to suggest we rewrite legacy headers. Just that we make sure we don't introduce more of them by simply not allowing new headers that parse differently (and maybe try to enforce that in header parsing code somehow too). And maybe that we clean legacy headers up based on investigating implementations and figuring out how to deal with spec-impl mismatches.

**Comment by mnot** [comment]
Ah, sorry.

I think the goal for structured headers is to capture *most* new headers, especially ones created by IETF, W3C and WHATWG. Raising that bar to *all* new headers would require it to be more expressive (and therefore more complex). Right now we're trying to figure out what the right level is.

From a process standpoint, I think we'd have a hard time requiring new headers to use it; aside from the issue above, plently of people mint new headers every day, and they can (and will) ignore that requirement.

I suppose we could say that it is RECOMMENDED that new standards-track headers use it, etc. Would that do it?

(BTW, the WG has adopted this draft, so discussion should really to go httpwg/http-extensions; feel free to create an issue there if you feel that something in the current draft needs to change).

**Comment by annevk** [comment]
Thanks, that's not quite what I'm looking for, but I also realized that we forever need byte accessors for header values due to APIs so folks can already do whatever they want.

Though there is still room for HTTP itself and APIs I suppose to expose a "get parsed header value" primitive that always uses this, except for legacy header code paths. But that might require nailing down all the legacy header code paths too.
