### ISSUE TITLE
Clarify the introduction

### ISSUE THREAD

**Issue by paulehoffman** [mnot/I-D#267]
Section 1 starts with "Some applications on the Web require the discovery of policy or other information about an origin...". It finishes with "this memo defines a path prefix in HTTP(S) URIs for these 'well-known locations'". The beginning of Section 1.1 makes it clear that "or other information" is not allowed in the author's eyes, but then the third paragraph goes on to use "and other metadata". 

Given that you have made it clear that you only intend .well-known/ to be used for what you consider site-wide metadata, this draft should be scrubbed of anything other than that.

**Comment by mnot** [comment]
It's not saying "policy" or "other information" is inappropriate, provided it's _about_ the origin. Will try to clarify.
