### ISSUE TITLE
Underlying data type

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#274]
Is it still appropriate to use JSON as the underlying data model, or should something like the [Item type   from Structured Headers](http://httpwg.org/http-extensions/draft-ietf-httpbis-header-structure.html#item) be used instead?

**Comment by asbjornu** [comment]
Could you please provide an example of how that item type looks like?

**Comment by mnot** [comment]
Sorry, not an item. I'm thinking (vaguely, for now) that rather than using JSON, something based upon the data model in structured headers makes more sense; would need to include something like-like, I suspect.
