### ISSUE TITLE
Tweaks

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#279]
From @britram:

(1) The document currently treats "end users" as a homogeneous group, but of course that's not the case, and in some cases there will be conflicts of interest among end users: say, buyers and sellers of products, or publishers and consumers of content, that from the point of view of the network and platforms they're using are both just users. This document implicitly treats such conflicts as out of scope, but it should explicitly do so to avoid confusion.

(2) On that point, the example given to define end user ("a person using a Web browser, mail client, or other agent that connects to the Internet") does not avoid what I find to be a common implicit assumption in both engineering and civil society discussion about users, that "using" the Internet is associated with consumption as opposed to production. There's nothing in the scope of the document that limits it, as such, but having additional examples ("a person hosting some information on a web server or via a publishing platform" for instance) might

(3) In general, since the document (correctly IMO) tries to avoid defining its operable terms ("end user", "harm", "benefit") too tightly, more (and diverse) examples would help the document a bit. I can try to spend some time coming up with useful ones and send a PR in my Copious Free Time if it'd help.

**Comment by britram** [comment]
amending point two, where I was apparently interrupted:

>  but having additional examples ("a person hosting some information on a web server or via a publishing platform" for instance) might...

...illustrate that we're concerned about the Internet as a medium for conversation, not a replacement for television.

**Comment by mnot** [comment]
1. Agreed. IIRC it used to be explicit, but that was lost somewhere along the way.

2. Agreed, and I think easy to fix. 

3. That would be VERY helpful.

**Comment by mnot** [comment]
I think this is addressed in [draft-iab-for-the-users](https://intarchboard.github.io/for-the-users/draft-iab-for-the-users.html); if not, please open an issue [here](https://github.com/intarchboard/for-the-users/issues). Thanks.
