### ISSUE TITLE
For the users: Just looking forward or also looking back?

### ISSUE THREAD

**Issue by sftcd** [mnot/I-D#292]
https://github.com/mnot/I-D/tree/gh-pages/for-the-users says:

"... the IETF tends to protect their interests over those of parties such as network operators or equipement (sic) vendors"

I'm not sure how historically true that is. I guess we could take that "we do this already" approach, or we could take the line that "this is what we should be doing" without claiming it as the historic norm. I'm not sure which tactic is likely more effective, but perhaps the latter one is more easily defended.

Resolution of this issue might affect how the later examples section is written.

**Comment by mnot** [comment]
I think this is addressed in [draft-iab-for-the-users](https://intarchboard.github.io/for-the-users/draft-iab-for-the-users.html); if not, please open an issue [here](https://github.com/intarchboard/for-the-users/issues). Thanks.
