### ISSUE TITLE
For the Users: "greatest good for the greatest number" 

### ISSUE THREAD

**Issue by wseltzer** [mnot/I-D#297]
The focus on end-user benefit is very helpful.  

At risk of getting into the weeds, I'm not sure its decision principles are (or need to be) fully worked out. In particular, utilitarian considerations of harm minimization aren't the only way to consider and balance end-user interests. Democratic principles of due process, protection of minority rights, and provision for individuals' collective action also aim to benefit the end-user. 

> When the needs of different end users conflict; for example, between governments and individuals, we again try to minimise harm - this time, to the greatest number and most specific of end users.

A different argument governments often make is that they *are* the means by which end-users (their citizens) express and protect their interests. Articulation of the principle can help to get through the stakeholder conflict about who speaks for the end-users.

**Comment by mnot** [comment]
That specific text has been removed; the doc has evolved a fair amount. Keeping this open because the 2nd paragraph is useful to keep in mind (thanks!).

**Comment by mnot** [comment]
I think this is addressed in [draft-iab-for-the-users](https://intarchboard.github.io/for-the-users/draft-iab-for-the-users.html); if not, please open an issue [here](https://github.com/intarchboard/for-the-users/issues). Thanks.
