### ISSUE TITLE
RFC 4941

### ISSUE THREAD

**Issue by coopdanger** [mnot/I-D#302]
RFC 4941 doesn't mitigate the potential issues associated with the uniqueness of an IPv6 prefix. RFC 4941 (and 7217 and 8064) mitigate the potential for uniqueness and stability of the interface identifier to be abused, but none of them are effective against abuse of the prefix's uniqueness if a prefix only gets used by a single host.

**Comment by mnot** [comment]
Could you suggest some text?

**Comment by coopdanger** [comment]
I think I would need to understand better what point you're trying to make with the example. Is this an exception to the guideline of prioritizing users? Or are the mitigation documents meant to exemplify how to prioritize users?

**Comment by mnot** [comment]
@britram was it you that supplied this text?
