### ISSUE TITLE
Inventing a new binary format instead of using standards

### ISSUE THREAD

**Issue by paulehoffman** [mnot/I-D#309]
Why does this document invent a new binary format instead of using one that has already been standardized, such as CBOR?

Requiring client and server implementations to create new parser code introduces a lot of new security threats.

CBOR's structure looks like it would create smaller headers than the current proposal.

**Comment by mnot** [comment]
There is a very real hazard that people will think that *any* CBOR is acceptable there. Besides, this wasn't a problem when creating similar formats -- such as HPACK, QPACK, etc.
