### ISSUE TITLE
Timing concerns for Link Hints

### ISSUE THREAD

**Issue by dret** [mnot/I-D#320]
over at https://github.com/dret/I-D/issues/141 we're wondering whether we should support link hints or not. the linkset draft is relatively close to completion, so we want to avoid creating dependencies that will slow us down. @mnot, what do you think about timing for that draft?

**Comment by mnot** [comment]
I think this is overcome by events, but if you want to try to get it in, we can talk about adoption. I'd think, however, that hopefully there shouldn't be a hard dependency...
