### ISSUE TITLE
Any chance of link-hints and linked-cache invalidation to become an RFC?

### ISSUE THREAD

**Issue by evert** [mnot/I-D#336]
Hi Mark!

Big fan of your work. We heavily make use of link hints and linked cache invalidation. I was curious if these are drafts that you're still interested in. They're excellent ideas and just wanted to let you know there's people out there that care.

If there's anything I can do to further these specs I would be happy to!

**Comment by asbjornu** [comment]
Since the specs are used in the API sphere, perhaps we could adopt them into the [HTTP API WG](https://datatracker.ietf.org/wg/httpapi/about/)?

**Comment by mnot** [comment]
Link Hints is in HTTPAPI. LCI, not sure.
