### ISSUE TITLE
Application Data Registry

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#37]
This isn't being used, and the use case it was created for doesn't seem to have materialised. Can / should we get rid of it?

**Comment by dret** [comment]
same here: not quite sure what the idea is, and never seen it used, so removing/deprecating would be a good idea.

**Comment by asbjornu** [comment]
@mnot Before deciding whether the registry should be removed, could you outline the arguments for creating it in the first place? What is its purpose?

**Comment by akuckartz** [comment]
:+1: for removing unneeded registry.

**Comment by mnot** [comment]
@asbjornu it was supposed to address the needs of the HTML WG in adding different kinds of information to the registry; they ended up not using it. Note that the current draft still allows the experts to add new fields to the registry; it's just not so formally coordinated (which IMO is unnecessary).

**Comment by asbjornu** [comment]
@mnot Thanks for the information. Good to know. :)
