### ISSUE TITLE
link relations for RDF

### ISSUE THREAD

**Issue by dret** [mnot/I-D#39]
when working with the SemWeb/RDF community, it becomes obvious that link relations (and any other registries that manage concepts through non-URI identifiers) are a challenge for that community. even if they want to (re-)use those concepts, they cannot legally do so within RDF, because RDF requires identifiers to be URIs.
would it make sense to include something in RFC 5988bis that would allow RDF representations to use registered link relations as URIs? It would not be pretty to do that, because then on the web, registered link relations would be strings, and on the semantic web, they would be some form of equivalent URI. but maybe such a solution would be better than not doing anything, and making it impossible for RDF-based models to properly use registered link relations at all?

**Comment by elf-pavlik** [comment]
Hi everyone, I wonder if we can add checklist with some clear :white_check_mark:   **ACTION** points to move forward here?

@tantek & @msporny do you see any possible issues with how HTML5 and RDFa1.1 define **rel** ?
* http://www.w3.org/TR/html5/document-metadata.html#attr-link-rel
* http://www.w3.org/TR/rdfa-syntax/#A-rel

**Comment by elf-pavlik** [comment]
@mnot @tantek while neither IANA and microformats do NOT provide stable URI for all the terms in open controlled vocabularies, which they manage. Would you see problem if someone else provided such stable URIs, for example via https://w3id.org/ ?
* https://w3id.org/iana/type
* https://w3id.org/microformats/h-entry

(or possibly using # pattern for such nice and small vocabularies)

* https://w3id.org/iana#type
* https://w3id.org/microformats#h-entry

If one day you decide to take responsibility for hosting resources returned when dereferencing those URIs, it would just take changing redirects on w3id.org

@msporny @kidehen @prototypo do you see such approach as appropriate and along intention behind w3id.org?

**Comment by msporny** [comment]
@elf-pavlik - yes, that approach is appropriate wrt. w3id.org. If IANA / IETF wants to add themselves to be a co-maintainer of the w3id.org website, it would be welcomed w/ open arms. The same invitation has been extended to W3C, but they'd like to publish terminology such as this in W3C-space. I expect that IANA / IETF will most likely want to do the same.

For schema.org, when they weren't publishing a reasonable JSON-LD context, the JSON-LD community took it upon itself to publish something via w3id.org and implementers just linked to the w3id.org context. This may or may not have pushed the schema.org folks to publish something themselves lest w3id.org ended up becoming the main location that developers would use to reference the JSON-LD schema.org context. So, w3id.org has been used to move these sorts of discussions forward before.

I have no horse in this race, just providing info for the rest in this thread that need to make the decision.

**Comment by prototypo** [comment]
+1

Regards,
Dave
--
http://about.me/david_wood

**Comment by dret** [comment]
just one word of caution: experience shows that when you create specs that say "you can refer to this concept by identifier a or b", the minority of implementations handle this correctly (see @jasnell's comment https://github.com/mnot/I-D/issues/39#issuecomment-30522032 and similar implementation experience from activity streams which also defined synonyms that weren't supported well by implementations). implementations mostly prefer a or b and use that preference consistently, and then stop being interoperable with those implementations that make the opposite choice.
so yes, there should be a way how data models that can only handle URI identifiers are given the opportunity to identify natively non-URI values from IANA registries. in an ideal world, this could even be approached in a way that it is not done on a per-registry basis, but consistently across (some of) them.

**Comment by kidehen** [comment]
On 2/23/15 8:52 AM, Manu Sporny wrote:
>
> @elf-pavlik <https://github.com/elf-pavlik> - yes, that approach is 
> appropriate wrt. w3id.org. If IANA / IETF wants to add themselves to 
> be a co-maintainer of the w3id.org website, it would be welcomed w/ 
> open arms. The same invitation has been extended to W3C, but they'd 
> like to publish terminology such as this in W3C-space. I expect that 
> IANA / IETF will most likely want to do the same.
>
> For schema.org, when they weren't publishing a reasonable JSON-LD 
> context, the JSON-LD community took it upon itself to publish 
> something via w3id.org and implementers just linked to the w3id.org 
> context. This may or may not have pushed the schema.org folks to 
> publish something themselves lest w3id.org ended up becoming the main 
> location that developers would use to reference the JSON-LD schema.org 
> context. So, w3id.org has been used to move these sorts of discussions 
> forward before.
>
> I have no horse in this race, just providing info for the rest in this 
> thread that need to make the decision.
>

I only have one horse in this race, and its all about making names 
interpretable using Linked Open Data patterns. That's it.

-- 
Regards,

Kingsley Idehen	
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by tantek** [comment]
Elf, this is not a reasonable assumption nor framing: "while neither IANA and microformats do NOT provide stable URI for all the terms in open controlled vocabularies, which they manage" thus I interpret the rest of your proposal as unnecessary.

How are you measuring such "stability" so as is to assert it (w3id) or lack thereof?

From my experience, both IANA and microformats appear have fairly good track records of "stable URI[s]". And by "fairly good" I mean no loss of URLs AFAIK in their entire history.

Such stable URLs seem to be an instance of: if it's working, don't fix it, don't make extra work for people.

Contrasting example: OpenSocial just killed all their URLs in their handoff to W3C.

Background: my expertise comes from personally having 12+ years of personal experience maintaining stable URLs (date-time-stamped permalinks) at my personal domain, and longer than that for non-date-stamped URLs. I know nothing of w3id, nor of the longevity of anyone else's experience here with maintaining personal stable URLs, so I don't know how to evaluate other opinions.

**Comment by dret** [comment]
@tantek, it is my understanding that when @elf-pavlik  talks about "provide stable URI for all the terms in open controlled vocabularies", he not only talks about defining URIs, but for the ability to dereference them and get something back as a response. which is an entirely different issue, imho, but i think this may be the slight misunderstanding between the two of you. please correct me if i am wrong, @elf-pavlik.

**Comment by kidehen** [comment]
On 2/24/15 3:59 AM, Erik Wilde wrote:
>
> @tantek <https://github.com/tantek>, it is my understanding that when 
> @elf-pavlik <https://github.com/elf-pavlik> talks about "provide 
> stable URI for all the terms in open controlled vocabularies", he not 
> only talks about defining URIs, but for the ability to dereference 
> them and get something back as a response. which is an entirely 
> different issue, imho, but i think this may be the slight 
> misunderstanding between the two of you. please correct me if i am 
> wrong, @elf-pavlik <https://github.com/elf-pavlik>.
>

Yes, this is all about URIs resolving to descriptions of what they 
identify.

Right now we have:

1. http://www.iana.org/assignments/link-relations/link-relations.txt
2. http://www.iana.org/assignments/link-relations/link-relations.xhtml
3. http://www.iana.org/assignments/link-relations/link-relations.xml
4. http://www.iana.org/assignments/link-relations/link-relations-1.csv

Simple solution options:

1. Tweak 
<http://www.iana.org/assignments/link-relations/link-relations.xhtml> by 
using <script/> to embed json-ld and turtle
2. Add http://www.iana.org/assignments/link-relations/link-relation.ttl
3. Add http://www.iana.org/assignments/link-relations/link-relations.jsonld.

I don't know who controls this domain, but the TURTLE and JSON docs can 
be prepared very easily for incorporation and we are then completely set 
with this matter.

-- 
Regards,

Kingsley Idehen	
Founder & CEO
OpenLink Software
Company Web: http://www.openlinksw.com
Personal Weblog 1: http://kidehen.blogspot.com
Personal Weblog 2: http://www.openlinksw.com/blog/~kidehen
Twitter Profile: https://twitter.com/kidehen
Google+ Profile: https://plus.google.com/+KingsleyIdehen/about
LinkedIn Profile: http://www.linkedin.com/in/kidehen
Personal WebID: http://kingsley.idehen.net/dataspace/person/kidehen#this

**Comment by elf-pavlik** [comment]
@kidehen do you have any suggestions for mentioned earlier on this thread http://microformats.org/wiki/existing-rel-values (HTML5 spec uses it as official registry of link relations!)

please also notice earlier comment by @darrelmiller 

> I see no reason why 5988bis could not indicate that all registered link relations could be resolved to a URI such as http://www.iana.org/assignments/link-relations/{relname} or something like that. In 5988 even extension link relations are not required to actually be serialized as URIs as long as there is some process to generate a URI identifier.

and reply by @jasnell 

> FWIW, this approach was attempted in RFC4287 (http://tools.ietf.org/search/rfc4287#section-4.2.7) but exceedingly few implementers would actually treat the registered short form as being equivalent to the absolute URI form. In fact, Apache Abdera is the only implementation I'm aware of that did. So the real question is: would implementers actually pay attention to this and implement it? I'm not so sure.

**Comment by elf-pavlik** [comment]
It looks that another big difference in using link-relations/predicates in RDF serializations and in HTTP Link Header relates to using them as in(re)verse. In Web Linking spec we find:
>The "rev" parameter has been used in the past to indicate that the
   semantics of the relationship are in the reverse direction.  That is,
   a link from A to B with REL="X" expresses the same relationship as a
   link from B to A with REV="X". "rev" is deprecated by this
   specification because it often confuses authors and readers; in most
   cases, using a separate relation type is preferable.

https://tools.ietf.org/html/rfc5988#section-5.3

While many people discourage defining separate relation for in(re)verse in RDF vocabularies since it may require OWL reasoning (owl:inverseOf) when processing the data:
https://lists.w3.org/Archives/Public/public-vocabs/2015Mar/0189.html

**Comment by timbl** [comment]
On 2015-04 -04, at 16:17, ☮ elf Pavlik ☮ <notifications@github.com> wrote:

> It looks that another big difference in using link-relations/predicates in RDF serializations and in HTTP Link Header relates to using them as in(re)verse. In Web Linking spec we find:
> 
> The "rev" parameter has been used in the past to indicate that the
> semantics of the relationship are in the reverse direction. That is,
> a link from A to B with REL="X" expresses the same relationship as a
> link from B to A with REV="X". "rev" is deprecated by this
> specification because it often confuses authors and readers; in most
> cases, using a separate relation type is preferable.
> 
> 

Yes the above passage is unfortunate and in the spec "against my better judgement" as they say.

I would personally encourage people to use "rev" as well as "rel', and to invent only one predicate not two.

It is worth starting a movement to have the spec changed, or the modern style to issue another best practice spec which is a "willful violation" of the current HTML one?

**Comment by elf-pavlik** [comment]
I believe most of the people participating in this issue will also attend [TPAC 2015](http://www.w3.org/2015/11/TPAC/), maybe it will give an opportunity to meet face 2 face and discuss possible improvements to current state of things?

As of today, attempts to navigate between link-relations and RDF predicates mismatch, results in proposals like for example @jasnell's http://www.w3.org/TR/activitystreams-vocabulary/ Which has tons of reverse properties defined on vocabulary level (20) and tries to introduce constructs like [as:Link](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-link) with [as:rel](http://www.w3.org/TR/activitystreams-vocabulary/#dfn-rel)

At the same time on http://microformats.org/wiki/existing-rel-values I see proposed relations with DCTERMS namespace e.g. *DCTERMS.creator* @tantek 
Also human and machine readable mappings for example between http://microformats.org/wiki/rel-publickey and https://w3id.org/security#publicKey (owl:equivalentProperty) could help with making things more inter-operable while allowing people who implement things to work with technology of their choice.

I really wish that people responsible for current state of things will make serious effort to engage in dialog about possible solutions. Especially that many possibilities for improvement exist and most likely just require solid evaluation by everyone involved.

**Comment by elf-pavlik** [comment]
@gkellogg in https://github.com/w3c/csvw/issues/297#issuecomment-90078110

> I can add it to th examples directory. I will also likely use it to create a cache IANA vocabulary for my Ruby RDF libraries, as users have been clamoring for this.
>```json
>{
  "url": "http://www.iana.org/assignments/link-relations/link-relations-1.csv",
  "tableSchema": {
    "aboutUrl": "{name}",
    "lang": "en",
    "columns": [
      {"name": "name", "title": "Relation Name", "propertyUrl": "rdfs:label"},
      {"name": "comment", "title": "Description", "propertyUrl": "rdfs:comment"},
      {"name": "type", "title": "Reference", "propertyUrl": "rdf:type", "valueUrl": "rdf:Property"},
      {"title": "Notes", "suppressOutput": true}
    ]
  }
}
>```

**Comment by elf-pavlik** [comment]
https://github.com/aaronpk/Micropub/issues/1#issuecomment-92421316

In issue above @tantek and [aaronpk](https://github.com/aaronpk) argue that registry recommended by WHATWG and W3C in HTM5 spec -  http://microformats.org/wiki/existing-rel-values also applies to HTTP Headers and using *micropub* and *webmention* there does NOT require additional registration with IANA.
In response to issue I raised that **relations not registered with IANA should use full URI** when used in **HTTP** Header. While for relations registered on microformats wiki can use short form but only when used as value of **HTML** *rel*/*rev* attribute.

>Note that extension relation types are REQUIRED to be absolute URIs
   in Link headers, and MUST be quoted if they contain a semicolon (";")
   or comma (",") (as these characters are used as delimiters in the
   header itself).

https://tools.ietf.org/html/rfc5988#section-5.3

I don't argue here for any particular solution, just raise issue that such unclear situation about link relations / rdf:Property **blessed** registry, and having different ones for HTTP, HTML (why not JSON), can have consequences in future interoperability. Here again lack of official URIs for link relations / rdf:Property(ies) defined in IANA and microformats *blessed* registries, prevents those, who want to stay  very precise about which particular terms they use, from simply using such URIs as truly unique identifiers :disappointed:

**Comment by mnot** [comment]
Reading over this issue, I think we're actually talking about a number of (hopefully separable) issues:

This issue is "how do I find a link for a registered relation type." I think the resolution is a modification of what I suggested way above (incorporating feedback from @dret). In "Registered Relation Types", add:

> Applications that wish to refer to registered relation types with a URI [RFC3986] MAY do so by prepending them with "http://www.iana.org/assignments/relation/". Note that the resulting strings are not considered equivalent to the registered relation types by many processors, and SHOULD NOT be serialised unless the application using link relations specifically allows them.

*(with possible adjustments to the prefix depending on decisions below)*

Another issue is "What are the rules for getting things into and maintaining the registry?" That's #40. 

Finally, there's "Where should the registry be hosted?" Provided #40 is dealt with adequately, this is mostly a question of who can meet the requirements, in terms of software, stability, resources, oversight, etc. I don't think that should have an issue number *or* be discussed until we figure out what those requirements are. 

@tantek, I'd love to have a discussion with you about the process used for the wiki over on #40.

**Comment by elf-pavlik** [comment]
@timbl @mnot @tantek sadly I don't see any progress in #40 :worried: 
If you all participate in [W3C TPAC 2015](http://www.w3.org/2015/10/TPAC/), maybe at least all three of you could discuss this issue there IRL?

Once again, I find current situation **harmful for The Internet & The Web ecosystem as a whole**! Having a different link relations registry for HTML5 media type and a different for HTTP Headers and all the non HTML5 media types doesn't seem to make any sense from technical perspective, and it seems more of a very unfortunate outcome of possible drama between standards organizations / working groups (happy to stand corrected here! and :+1: / :-1: from others following this thread very welcomed)

IMO we also need stable official prefix ASAP to use with relations like: **[describes](https://tools.ietf.org/html/rfc6892)/[descirbedBy](https://dvcs.w3.org/hg/ldpwg/raw-file/default/ldp.html#link-relation-describedby)** when used in JSON-LD, Turle, RDFa and all the other [RDF serializations](http://www.w3.org/TR/rdf11-new/#section-serializations) (eg. https://github.com/w3c/csvw/issues/297#issuecomment-78284500)

**Comment by asbjornu** [comment]
I agree with @elf-pavlik. The current situation is indeed harmful and even more fragmentation is being suggested as we write this, by different RDF based vocabularies defining their own semantics and names for relations that already exist in IANA. Not having a single registry for this that can support RDF, HTML5 and HTTP headers is quite terrible.

@timbl writes:
> I would personally encourage people to use "rev" as well as "rel', and to invent only one predicate not two.

In an ideal world, I agree, but as per [the research done while creating HTML5](https://blog.whatwg.org/the-road-to-html-5-link-relations#rel-author):

> Given that `rev=made` was [the only significant non-typo usage of the rev attribute](https://developers.google.com/webmasters/state-of-the-web/2005/linkrels?csw=1), HTML 5 added `rel=author` to make up for the loss of `rev=made` in HTML 4, thus allowing the working group to obsolete the rev attribute altogether. Other than the un/semi/sortof-documented `rev=made` value, people typo the "rev" attribute more often than they intentionally use it, which suggests that the world would be better off if validators could flag it as non-conforming.

As [`rev` is obsoleted in HTML5](http://www.w3.org/TR/html-markup/a.html#a), and given the research that led to that decision, I think it's wise to obsolete it in all other media types too and instead pay the overhead it is to define two inverse predicates.

**Comment by niklasl** [comment]
:+1: Certainly agree. Adding some simple RDFS statements about the IANA relations in one of the official representations has come up for many years. Now there might be interest enough and traction to make it happen. It would be quite simple to do so (e.g. by adding some RDFa like in http://www.w3.org/1999/xhtml/vocab#).

The "reinvention" of them in various vocabularies is understandable but fragmenting. That can be made interoperable by equivalence statements linking to the IANA "base properties".

**Comment by stain** [comment]
+1 to add RDFa or similar, for both link relations and media types. Link types and media types are used beyond HTTP headers and need stable URIs, not just "The word `disclosure` in that IANA Link registry you know".

For media types I have previously used http://purl.org/NET/mediatypes/ as not all media types have URIs at IANA - http://www.iana.org/assignments/media-types/text/plain is the most glaring example - but now http://mediatypes.appspot.com/ (as the purl redirect to) has stopped working. I agree with @dret that these should be hosted by IANA instead of third-parties.

It should be possible to edit [link-relations.xsl](http://www.iana.org/assignments/link-relations/link-relations.xsl) and/or [iana-registry.xsl](http://www.iana.org/assignments/_support/iana-registry.xsl) to generate RDFa.

See also this RDF/XML approach by @acoburn:
https://github.com/projecthydra-labs/rdf-vocab/commit/4b8457c828b94cfed60315d10c91913d38ae5a8c

**Comment by niklasl** [comment]
@stain Indeed, tweaking the relevant part of link-relations.xsl to something like:

```xslt
<xsl:when test="../@id = 'link-relations-1'">
  <tr typeof="owl:ObjectProperty" resource="http://www.iana.org/assignments/relation/{iana:value}">
    <td property="skos:notation"><xsl:value-of select="iana:value"/></td>
    <td property="dc:description"><xsl:apply-templates select="iana:description"/></td>
    <td rel="dc:references"><xsl:apply-templates select="iana:spec"/></td>
    <td>
      <xsl:if test="iana:note">
        <xsl:attribute name="property">skos:note</xsl:attribute>
      </xsl:if>
      <xsl:value-of select="iana:note"/>
    </td>
  </tr>
</xsl:when>
```

would do the trick.

**Comment by stain** [comment]
great, @niklasl - I made something along those lines - perhaps you could help me finish it? Not sure if owl:ObjectProperty is appropriate, so I went with just `skos:Concept`

See https://gist.github.com/stain/d4656bede203b7c3ba4e
Feel free to use. CC0 or whatever.

**Comment by stain** [comment]
I used URIs like http://www.iana.org/assignments/relation as it redirects correctly to the XHTML, I didn't think http://www.iana.org/assignments/link-relations/link-relations.xhtml#relation would be a nice identifier. (A compromise could be http://www.iana.org/assignments/link-relations#relation which with a bit of `id="relation` would scroll to the right line)

**Comment by mnot** [comment]
I've created #140 to capture the specific issue about registered relation types.

#40 is about the management of the registry itself.

**Comment by IS4Code** [comment]
It's been 8 years, has anything improved? At least the redirect from <code>http\://www.iana.org/assignments/relation/*rel*</code> is there, but no semantic improvements to the XSL.
