### ISSUE TITLE
Registration procedure

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#40]
(from Bjoern)

Given that

  Within at most 14 days of the request, the Designated Expert(s) will
  either approve or deny the registration request, communicating this
  decision to the review list and IANA. ...

does not happen in practise, revising the registration process should be
a primary concern.

This issue includes discussion of how the registry should be managed, or *not* managed.

**Comment by elf-pavlik** [comment]
Does this issue relates only to [Link Relations Registry](https://www.iana.org/assignments/link-relations/link-relations.xhtml) or also [other registries](https://www.iana.org/protocols)?
* [Media Types](http://www.iana.org/assignments/media-types/media-types.xhtml)
* [The Profile URI Registry](https://tools.ietf.org/html/rfc7284)
* [OAuth Parameters](http://www.iana.org/assignments/oauth-parameters/oauth-parameters.xhtml)
* [Webfinger Parameters](https://www.iana.org/assignments/webfinger/webfinger.xhtml) (empty)
* [vCard Elements](https://www.iana.org/assignments/vcard-elements/vcard-elements.xhtml#properties)
* [iCalendar Element Registries](https://www.iana.org/assignments/icalendar/icalendar.xhtml)
* etc.

For example vCard Elements has currently URIs defined for use with RDF in [W3C vCard Ontology](http://www.w3.org/TR/vcard-rdf/), hopefully not duplicated again by including them also among URIs in [Microformats namespace](https://github.com/rhiaro/mf2rdf), in particular [mf:h-card](http://microformats.org/wiki/h-card). Similar iCalendar has some URIs defined for use with RDF in [W3C RDF Calendar](http://www.w3.org/TR/rdfcal/) and again possibly duplicated in [mf:h-event](http://microformats.org/wiki/h-event). Which in a way relates to various issues with coordination already discussed in #39

**Comment by mnot** [comment]
Only link relations.

**Comment by dret** [comment]
even though the 14 day deadline may not always have been strictly followed, it seems that the spirit of the review process is followed (have expert reviews and give feedback and include the value if accepted). i have been following that particular registry very closely, and personally have been happy with how the registration process has been handled so far.

**Comment by mnot** [comment]
I think a good portion of the problem is friction; it's not reasonable to ask people to subscribe to a mailing list to submit something.

A form (e.g., like that for media types, but better) might do the trick, but I want to think through the workflow. 

A wiki has been brought up many times. I'm not against it, but looking at the current one:
  http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions

... I'm not sure it's an improvement...

**Comment by dret** [comment]
the wiki part is where the "workflow-based registries are pure evil" people lose me. the "wiki registries" have some workflow part to it, but of course badly done, because that's what wikis are bad at. so in the end it's a poorly managed registry that seems to just bear the cooler name "wiki". and whatever the technical platform is, it seems to me that some form of review/feedback/consensus loop is a good idea. it's not that i'm a huge fan of IANA's way of doing things, but it seems to me that even if their technical foundation may be quite outdated by now, the general idea and process still are appropriate.

**Comment by elf-pavlik** [comment]
> A wiki has been brought up many times. I'm not against it, but looking at the current one:
http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions

> ... I'm not sure it's an improvement...

On mentioned wiki I see proposals like DCTERMS.rightsHolder and many others saying

>Requires Dublin Core namespace declaration: `<link rel="schema.DCTERMS" href="http://purl.org/dc/terms/" />`

They [stay in proposed state since March 2015](http://microformats.org/wiki/index.php?title=existing-rel-values&diff=64849&oldid=64838). I also struggle to understand benefit of using `rel="DCTERMS.rightsHolder"` over `rel="http://purl.org/dc/terms/rightsHolder"`

I also notice there proposal `http://docs.oasis-open.org/ns/cmis/link/200908/acl`, which I understood more as attempt to make this URI more broadly known that need to register it.

Maybe IANA experts responsible for link relations could offer their feedback on some of the proposals we can find on that wiki? It could possibly highlight reasons for having certain lightweight process in place?

**Comment by asbjornu** [comment]
I'm in perfect line with @elf-pavlik on this. :+1:

**Comment by dret** [comment]
On 2015-10-15 22:35, elf Pavlik wrote:
> Maybe IANA experts responsible for link relations could offer their
> feedback on some of the proposals we can find on that wiki? It could
> possibly highlight reasons for having certain lightweight process in place?

i think it's clear where the IANA process is lacking:

- no easy way to find a history of registry updates.
- no easy way to contribute other than by email.

afaict, these things would be fairly easy to fix with better 
interlinking between the registry and whatever medium is used for 
discussions. that could be done with a wiki, but wikis tend to be pretty 
bad at this kind of structured information. from the discussion i have 
heard, mostly they started and ended with

IANA registry (email list!) = bad
wiki (no email list!) = good

having worked with a large number of registries (shared across pretty 
large developer teams), i was never impressed with the ease of use or 
understanding that wikis provide (we tried simple ones and structured 
ones and they all failed after getting past the point where there's not 
so much data to handle).

maybe a better approach would be to first list the ways in which one 
would want to improve/change the current process (maybe even saying 
why), and then look at which solution would work best for that. my 
personal feeling is that something a la github might be better, but even 
there it is maybe still lacking the kind of structure one would probably 
want to have to run a larger number of registries.

i'd be more than happy trying to help improving the process, but as mark 
pointed out, simply yelling "wiki!" and claiming that this is better 
than what IANA has may not be the best way to go about this.

**Comment by elf-pavlik** [comment]
Actually I have impression that http://microformats.org/wiki/existing-rel-values#HTML5_link_type_extensions doesn't work that well at all! :-1: 

:+1: something like Pull Request workflow with Github/Gitlab discussion thread attached, it seems to work very fast for example with with https://github.com/perma-id/w3id.org

**Comment by akuckartz** [comment]
I agree with @elf-pavlik that URIs should be used. URLs preferrred!

**Comment by dret** [comment]
On 2015-10-16 10:07, Andreas Kuckartz wrote:
> I agree with @elf-pavlik <https://github.com/elf-pavlik> that URIs
> should be used. URLs preferrred!

this issue is not about changing the nature of link relation types. 
these are and will remain strings. this issue is just about how to maybe 
improve the way in which those strings are registered. for the question 
of how those may be used in environments that don't work well with 
non-URI identifiers, please refer to #140.

**Comment by asbjornu** [comment]
I too think pull requests are a better tool to aid in the process than a chaotic wiki. Pull requests provide a natural place for discussion of the proposed change before it is accepted and merged. With tags and "releases" on GitHub, you can track version numbers in a user friendly way too. And `readme.md` provides a pretty thoughtful rendering of the repository's documentation.

I find GitHub a rather good fit for the entire process. If hosting the registry on another domain than github.com is important, [GitHub Pages](https://pages.github.com/) might be a solution.

**Comment by mnot** [comment]
Hm. I wonder if we simply need to define the guarantees that that the registration process offers, but leave the actual mechanics of operation up to the Expert(s), and say that IANA will put text on the registry page to facilitate that at the direction of the Expert(s).

That way, we could set up a Github repo (perhaps plus a Google form for those who don't want to create a Github account) to do the discussion component.

**Comment by dret** [comment]
to me, that's definitely the way to go; say what the process should accomplish and how (from a workflow perspective). how to implement it is something else, and usually can be accomplished with all kinds of implementation platforms. to me, that's where the "IANA vs. Wiki" discussions failed to focus on the aspects that actually matter.
however, in the end there has to be one designated implementation that is the blessed one, or else you may end up with the situation that we're currently in, with the IANA registry being in place and the official one, but an competing implementation being provided and championed by one specific community. for outsiders just looking for which values are registered, this just looks odd and confusing, and very understandably so.

**Comment by mnot** [comment]
OK, I'm going to start working on text to that effect; I suspect we still need to hammer through what the process requirements should be on this issue.

In the meantime, we also need to consider #144.

**Comment by asbjornu** [comment]
Sounds good. The process is more important than the tools. Although I think GitHub pull requests are an excellent tool on which the process can be modelled. :-)
