### ISSUE TITLE
RNC schema, and the extension model in general

### ISSUE THREAD

**Issue by dret** [mnot/I-D#42]
currently, the text in appendix A makes statements about how extensions should be serialized, but the RNC schema does not attempt to capture those constraints. which may be fine, but it also may confuse readers when they try to match what the text is saying to what the schema is doing.
maybe this is touching upon the bigger issue of how extensibility is defined: is the extensibility essentially JSON-based and the XML syntax then has to reflect that in some form of JSONish structure? another approach could be to leave this open, so that for example users of the XML media type would be open to define XML-based extensions, but then these of course would have no easy mapping into a JSON variant.
this is probably the general problem (that's essentially the same for home documents) whether the extension model is based on one particular metamodel, and claims that all extensions must follow it (even if they might only be used in a serialization that's based on a different metamodel).
i guess in the end all this boils down to is bascially your "XML or JSON? Just choose!" blog post and its claim that a hybrid tends to look weird in places. the question then simply is how to manage/constrain the weirdness.
one possibility to avoid the "metamodels are us" conundrum could be to leave it open to extensions to define how they are supposed to be serialized in different metamodels. this includes the possibility that an extension would only say how it is serialized in JSON (or XML), and then there would be no reliable way to tell how it should be used in a different representation. this would avoid the need for a custom metamodel (or a preferred one such as JSON), but place the burden on extensions to explicitly define how they're supposed to be used in different serializations.

**Comment by mnot** [comment]
Think this was http-problem; published.

**Comment by dret** [comment]
yup, it was. the same problem applies to home documents, btw, when looking at the JSON and XML syntaxes (but there it's currently two separate drafts).
