### ISSUE TITLE
draft-nottingham-http-problem-06

### ISSUE THREAD

**Issue by MajorBreakfast** [mnot/I-D#45]
@steveklabnik, the person who is currently leading the efforts of developing the [json-api](jsonapi.org) spec suggested that I should post my concerns about the http-problem specification right at the source (I'm guessing that's here).

I've written a lengthy comment about it: https://github.com/json-api/json-api/issues/7#issuecomment-34739285. It would be great if you were willing to discuss any improvements! (Here)

**Comment by mnot** [comment]
We're trying to get the spec to WGLC in the apps area WG, and I realised we never closed this discussion out. Sorry.

AFAICT, the major points left:

* "type" should be shorter. See resolution to #104 - is that better?
* "title" is to convey a quick, human-readable name for the error, whereas "type" is to identify it to machines. Make sense?

Anything else?

Thanks,

**Comment by mnot** [comment]
Not hearing anything, so closing.
