### ISSUE TITLE
Accept-Post in draft-nottingham-link-hint

### ISSUE THREAD

**Issue by dret** [mnot/I-D#55]
"accept-post" as it is currently defined in the draft-nottingham-link-hint draft works different from the current proposal in http://tools.ietf.org/html/draft-wilde-accept-post. it would be good to align the way in which these fields work. Currently, the "accept-post" of link hints allows a list of specific media types, whereas the Accept-Post header field may contain "media ranges".

**Comment by mnot** [comment]
Hm. The use cases for this seem to be along the lines of "this resource accepts any format for PUT" or "this resource accept any `image/*` format for POST".

I'm not sure that this is the right place to indicate these semantics -- it feels like we're doing validation by media type. Much better would be to bake the semantics into the link relation type of that resource.

OTOH HTML does it in form uploads with `accept`.

I could see it working for `AcceptPut`; I have a harder time with it for `AcceptPost` and especially for `AcceptPatch`. Just not sure the added complexity is worth it.

**Comment by dret** [comment]
FYI: the draft referenced above is no longer active. the W3C LDP group ended up registering `Accept-Post` directly in the LDP spec: https://www.w3.org/TR/ldp/#header-accept-post

**Comment by dret** [comment]
as discussed in #192, maybe it's worth considering splitting home documents and the general concept of link descriptions/hints?

**Comment by handrews** [comment]
> as discussed in #192, maybe it's worth considering splitting home documents and the general concept of link descriptions/hints?

I'd love a separate JSON-based HTTP hints spec.  People keep wanting it in JSON Hyper-Schema, although my preference is also to look more towards link relations for this.  But if we must have hints a shared JSON format for them would be useful.

**Comment by mnot** [comment]
@dret LDP needs to go and actually register that header field with IANA, not just put it in a document.

**Comment by dret** [comment]
On 2017-02-15 17:00, Henry Andrews wrote:
> I'd love a separate JSON-based HTTP hints spec. People keep wanting it
> in JSON Hyper-Schema, although my preference is also to look more
> towards link relations for this. But if we must have hints a shared JSON
> format for them would be useful.

thanks for the feedback, and i think it may be at least a direction 
worth exploring. basically, @mnot and i both had the same/similar idea 
at some point, and we both produced drafts:

* https://tools.ietf.org/html/draft-nottingham-link-hint
* https://tools.ietf.org/html/draft-wilde-link-desc

both are expired now and partially overlap, but they could provide 
starting points to think about what such a hints/descriptions spec might 
look like.

**Comment by dret** [comment]
On 2017-02-16 01:34, Mark Nottingham wrote:
> @dret <https://github.com/dret> LDP needs to go and actually register
> that header field with IANA, not just put it in a document.

i raised that point a couple of times with the team, but will do it 
again. thanks for the reminder!
