### ISSUE TITLE
Context of link header

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#61]
RFC5988, 5.2:

     By default, the context of a link conveyed in the Link header field
     is the IRI of the requested resource.

This means that the Link in a request has a context of the requested resource. Using the request representation itself might be more sensible.

See:
  http://httpwg.github.io/specs/rfc7231.html#identification

**Comment by kidehen** [comment]
@mnot has this issued been attended to in HTTP 2.0?

**Comment by mnot** [comment]
HTTP/2 doesn't talk about semantics; this would need to be an errata or update to 5988.

**Comment by kidehen** [comment]
@mnot -- any errata or update to <https://github.com/mnot/I-D/labels/rfc5988bis#this>  in regards to this matter? Ideally, I don't want to be using custom headers if Link: offers me the ability to identify relations scoped to an HTTP request.

**Comment by mnot** [comment]
This is too big a change to be an errata. This repo is working on an update, but it's not official, and won't be for some time, I reckon. Even if I pull my finger out and push a revision, it'll take a while to wind through IETF process.

**Comment by kidehen** [comment]
@mnot :  So I am to assume right not that the powerful Link: header is to be reduced to confines of its context being scoped to what's identified by the request IRI? That's quite a bug to leave lingering for so long. As you know, Link: is a powerful mechanism for reducing custom HTTP header explosion.
