### ISSUE TITLE
"safe" hint Link extension param or link relation

### ISSUE THREAD

**Issue by jasnell** [mnot/I-D#64]
Something to consider to go along with the safe-hint. To allow a server to advertise that it offers a "safe" alternative to any given resource:

```
Link: <http://example.org>; rel="alternate"; safe
```

The implication here would be that by default, the given resource may not be safe, but that the "safe" alternative will be provided if "Prefer: safe" is included in the request.

The alternative is to use a "safe" link relation:

```
Link: <http://example.org/safe-alternative>; rel="safe-alternate"
```

The implication here is that the linked resource is a "safe" alternative to the context resource, regardless of whether "Prefer: safe" is included in the request.

**Comment by mnot** [comment]
Doesn't look like `safe` is going forward; the IESG knocked it back and it *appears* that Microsoft is no longer implementing.
