### ISSUE TITLE
camelCase

### ISSUE THREAD

**Issue by mnot** [mnot/I-D#76]
for the JS people.

**Comment by RubenVerborgh** [comment]
This is definitely important; was the first thing I noticed.

**Comment by mnot** [comment]
Any preferences between camelCase and CamelCase? What are the cool kids doing these days?

**Comment by asbjornu** [comment]
The convention in JavaScript is inherited from Java, which is `lowerCamelCase`.

**Comment by akuckartz** [comment]
For those interested in history: camelCase and CamelCase were first introduced in Smalltalk (which is still cool, see http://squeak.org/ :-).
