### ISSUE TITLE
Remove AAD from encryption

### ISSUE THREAD

**Issue by martinthomson** [mnot/I-D#90]
The discriminator string probably isn't needed since we munge the CEK with a string that has a similar function.  And the record index is part of the IV.

Jim Schaad is convinced that you need to roll the tag from the previous block in to prevent substitution attacks, but I think you are screwed at that point anyway.

Run by @ekr first.

**Comment by mnot** [comment]
@ekr?

**Comment by ekr** [comment]
I don't think I understand the proposal. Can you explain exactly what is intended?

**Comment by martinthomson** [comment]
There are two things in the AAD: 
1. a discriminator string that identifies this as being encrypted with this specific scheme.  This makes substitution into or out of other encryption formats difficult.
2. the sequence number of the block, which makes it difficult to move records around, reorder, drop, etc...

(Basically the design is ripped from the TLS record format).

The idea is that neither is strictly needed. The CEK is derived from the original key with a similar discriminator string, addressing point 1.  And the record sequence number forms the IV.

**Comment by ekr** [comment]
Is there some reason not to include these?

**Comment by martinthomson** [comment]
That's not a particularly good reason to keep them if they are indeed redundant.

**Comment by ekr** [comment]
I believe we do not need the discriminator string, but I would advise checking with a cryptographer before removing the sequence number.
