### ISSUE TITLE
Padding change

### ISSUE THREAD

**Issue by martinthomson** [mnot/I-D#91]
Jim Schaad suggests that padding being zero is bad if AES-GCM ever loses its inviolate IND-CCA(2) status.  That would open up some known plaintext attacks, probably similar to those that people are getting excited about with in RC4.  I'm not concerned, but I think that it's worth checking to see if this is worth addressing.

A simple change would be to insist on all the octets being a repeat of the counter value, similar to how CMS does it (though CMS padding is 1-255 bytes because zero is not allowed for a reason I can't fathom).

**Comment by mnot** [comment]
Call on the collective wisdom of the crypto avengers and deliver a verdict.

**Comment by mnot** [comment]
Closing this; @martinthomson I trust you've taken care of this in your copy.
