### ISSUE TITLE
Consider Encryption header field split

### ISSUE THREAD

**Issue by martinthomson** [mnot/I-D#92]
Logically, there are two functions for this header field:
* To describe the encryption (nonce and keyid)
* To describe the key derivation for a given keyid.

@bifurcation suggests that two header fields be used, if only to make the story a little easier to tell.

We can use the former to say: "assume a shared key with ID X", then the latter one can deal with the business of actually describing how that key can be derived.  He also suggests that JWK is a useful construct for key description/conveyance.

**Comment by mnot** [comment]
Interesting. Not as sure as JWK as *the* way to do it, but it might be interesting as an option. WDYT?

**Comment by martinthomson** [comment]
I wasn't thinking that JWK was the only option, or even *an* option in the core specification, but I can certainly see how a split might make it easier to explain.

**Comment by mnot** [comment]
SGTM.
